package com.example.projeto_pokedex_app;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;

public class PokemonDataSeeder {

    public static void seedInitialData(SQLiteDatabase db) {
        //GEN 1
        addPokemon(db, "Bulbasaur", "Grass", "Poison", 1, "Bulbasaur is a small, quadruped Pokémon with a green body and a plant bulb on its back.");
        addPokemon(db, "Ivysaur", "Grass", "Poison", 1, "Ivysaur is the evolved form of Bulbasaur and has a large flower blooming on its back.");
        addPokemon(db, "Venusaur", "Grass", "Poison", 1, "Venusaur is the final form of Bulbasaur, with a massive flower that can absorb sunlight.");
        addPokemon(db, "Charmander", "Fire", "", 1, "Charmander is a small lizard-like Pokémon with a flame on its tail.");
        addPokemon(db, "Charmeleon", "Fire", "", 1, "Charmeleon is the evolved form of Charmander, known for its aggressive nature.");
        addPokemon(db, "Charizard", "Fire", "Flying", 1, "Charizard is the final form of Charmander, capable of breathing fire and flying.");
        addPokemon(db, "Squirtle", "Water", "", 1, "Squirtle is a small turtle Pokémon known for its water abilities.");
        addPokemon(db, "Wartortle", "Water", "", 1, "Wartortle is the evolved form of Squirtle, with a bushy tail.");
        addPokemon(db, "Blastoise", "Water", "", 1, "Blastoise is the final form of Squirtle, equipped with powerful water cannons.");
        addPokemon(db, "Caterpie", "Bug", "", 1, "Caterpie is a small caterpillar Pokémon known for its ability to evolve quickly.");
        addPokemon(db, "Metapod", "Bug", "", 1, "Metapod is the cocoon stage of Caterpie, known for its hard shell.");
        addPokemon(db, "Butterfree", "Bug", "Flying", 1, "Butterfree is the final form of Caterpie, known for its beautiful wings.");
        addPokemon(db, "Weedle", "Bug", "Poison", 1, "Weedle is a small, worm-like Pokémon that can produce a toxic stinger.");
        addPokemon(db, "Kakuna", "Bug", "Poison", 1, "Kakuna is the cocoon stage of Weedle, known for its hard exterior.");
        addPokemon(db, "Beedrill", "Bug", "Poison", 1, "Beedrill is the final form of Weedle, known for its stingers.");
        addPokemon(db, "Pidgey", "Normal", "Flying", 1, "Pidgey is a small bird Pokémon known for its flying abilities.");
        addPokemon(db, "Pidgeotto", "Normal", "Flying", 1, "Pidgeotto is the evolved form of Pidgey, known for its speed.");
        addPokemon(db, "Pidgeot", "Normal", "Flying", 1, "Pidgeot is the final form of Pidgey, known for its powerful wings.");
        addPokemon(db, "Rattata", "Normal", "", 1, "Rattata is a small rat Pokémon known for its quick movements.");
        addPokemon(db, "Raticate", "Normal", "", 1, "Raticate is the evolved form of Rattata, known for its large teeth.");
        addPokemon(db, "Spearow", "Normal", "Flying", 1, "Spearow is a small bird Pokémon known for its aggressive nature.");
        addPokemon(db, "Fearow", "Normal", "Flying", 1, "Fearow is the evolved form of Spearow, known for its speed and power.");
        addPokemon(db, "Ekans", "Poison", "", 1, "Ekans is a snake Pokémon that can coil around its prey.");
        addPokemon(db, "Arbok", "Poison", "", 1, "Arbok is the evolved form of Ekans, known for its intimidating hood.");
        addPokemon(db, "Pikachu", "Electric", "", 1, "Pikachu is a small, mouse-like Pokémon known for its electric abilities.");
        addPokemon(db, "Raichu", "Electric", "", 1, "Raichu is the evolved form of Pikachu and is larger and more powerful.");
        addPokemon(db, "Sandshrew", "Ground", "", 1, "Sandshrew is a small, burrowing Pokémon known for its hard shell.");
        addPokemon(db, "Sandslash", "Ground", "", 1, "Sandslash is the evolved form of Sandshrew, known for its sharp claws.");
        addPokemon(db, "Nidoran♀", "Poison", "", 1, "Nidoran♀ is a small, rabbit-like Pokémon known for its defensive capabilities.");
        addPokemon(db, "Nidorina", "Poison", "", 1, "Nidorina is the evolved form of Nidoran♀, known for its nurturing nature.");
        addPokemon(db, "Nidoqueen", "Poison", "Ground", 1, "Nidoqueen is the final form of Nidoran♀, known for its protective nature.");
        addPokemon(db, "Nidoran♂", "Poison", "", 1, "Nidoran♂ is a small, rabbit-like Pokémon known for its aggressive behavior.");
        addPokemon(db, "Nidorino", "Poison", "", 1, "Nidorino is the evolved form of Nidoran♂, known for its fighting abilities.");
        addPokemon(db, "Nidoking", "Poison", "Ground", 1, "Nidoking is the final form of Nidoran♂, known for its brute strength.");
        addPokemon(db, "Clefairy", "Fairy", "", 1, "Clefairy is a small, fairy-like Pokémon known for its playful nature.");
        addPokemon(db, "Clefable", "Fairy", "", 1, "Clefable is the evolved form of Clefairy, known for its magical abilities.");
        addPokemon(db, "Vulpix", "Fire", "", 1, "Vulpix is a small fox Pokémon known for its six orange tails.");
        addPokemon(db, "Ninetales", "Fire", "", 1, "Ninetales is the evolved form of Vulpix, known for its mystical powers.");
        addPokemon(db, "Jigglypuff", "Normal", "Fairy", 1, "Jigglypuff is a balloon-like Pokémon known for its singing ability.");
        addPokemon(db, "Wigglytuff", "Normal", "Fairy", 1, "Wigglytuff is the evolved form of Jigglypuff, known for its large size.");
        addPokemon(db, "Zubat", "Poison", "Flying", 1, "Zubat is a bat Pokémon known for its echolocation abilities.");
        addPokemon(db, "Golbat", "Poison", "Flying", 1, "Golbat is the evolved form of Zubat, known for its large fangs.");
        addPokemon(db, "Oddish", "Grass", "Poison", 1, "Oddish is a small plant Pokémon that can absorb sunlight.");
        addPokemon(db, "Gloom", "Grass", "Poison", 1, "Gloom is the evolved form of Oddish, known for its stinky odor.");
        addPokemon(db, "Vileplume", "Grass", "Poison", 1, "Vileplume is the final form of Oddish, known for its large flower.");
        addPokemon(db, "Paras", "Bug", "Grass", 1, "Paras is a bug Pokémon that is known for its mushroom-like parasites.");
        addPokemon(db, "Parasect", "Bug", "Grass", 1, "Parasect is the evolved form of Paras, known for its spores.");
        addPokemon(db, "Venonat", "Bug", "Poison", 1, "Venonat is a bug Pokémon known for its large, sensitive eyes.");
        addPokemon(db, "Venomoth", "Bug", "Poison", 1, "Venomoth is the evolved form of Venonat, known for its beautiful wings.");
        addPokemon(db, "Diglett", "Ground", "", 1, "Diglett is a small, mole-like Pokémon known for its underground abilities.");
        addPokemon(db, "Dugtrio", "Ground", "", 1, "Dugtrio is the evolved form of Diglett, known for its speed and teamwork.");
        addPokemon(db, "Meowth", "Normal", "", 1, "Meowth is a cat Pokémon known for its ability to speak.");
        addPokemon(db, "Persian", "Normal", "", 1, "Persian is the evolved form of Meowth, known for its elegance.");
        addPokemon(db, "Psyduck", "Water", "", 1, "Psyduck is a duck Pokémon known for its frequent headaches.");
        addPokemon(db, "Golduck", "Water", "", 1, "Golduck is the evolved form of Psyduck, known for its swimming abilities.");
        addPokemon(db, "Poliwag", "Water", "", 1, "Poliwag is a small tadpole Pokémon known for its spiral tail.");
        addPokemon(db, "Poliwhirl", "Water", "", 1, "Poliwhirl is the evolved form of Poliwag, known for its swirling pattern.");
        addPokemon(db, "Poliwrath", "Water", "Fighting", 1, "Poliwrath is the final form of Poliwag, known for its strength.");
        addPokemon(db, "Abra", "Psychic", "", 1, "Abra is a psychic Pokémon that is known for its teleportation ability.");
        addPokemon(db, "Kadabra", "Psychic", "", 1, "Kadabra is the evolved form of Abra, known for its psychic powers.");
        addPokemon(db, "Alakazam", "Psychic", "", 1, "Alakazam is the final form of Abra, known for its intelligence and speed.");
        addPokemon(db, "Machop", "Fighting", "", 1, "Machop is a small fighting Pokémon known for its strength.");
        addPokemon(db, "Machoke", "Fighting", "", 1, "Machoke is the evolved form of Machop, known for its muscles.");
        addPokemon(db, "Machamp", "Fighting", "", 1, "Machamp is the final form of Machop, known for its four arms.");
        addPokemon(db, "Bellsprout", "Grass", "Poison", 1, "Bellsprout is a plant Pokémon that can stand on its roots.");
        addPokemon(db, "Weepinbell", "Grass", "Poison", 1, "Weepinbell is the evolved form of Bellsprout, known for its bell shape.");
        addPokemon(db, "Victreebel", "Grass", "Poison", 1, "Victreebel is the final form of Bellsprout, known for its carnivorous nature.");
        addPokemon(db, "Tentacool", "Water", "Poison", 1, "Tentacool is a jellyfish Pokémon that can release toxins.");
        addPokemon(db, "Tentacruel", "Water", "Poison", 1, "Tentacruel is the evolved form of Tentacool, known for its large tentacles.");
        addPokemon(db, "Geodude", "Rock", "Ground", 1, "Geodude is a rock Pokémon that can be found in caves.");
        addPokemon(db, "Graveler", "Rock", "Ground", 1, "Graveler is the evolved form of Geodude, known for its boulders.");
        addPokemon(db, "Golem", "Rock", "Ground", 1, "Golem is the final form of Geodude, known for its hard shell.");
        addPokemon(db, "Ponyta", "Fire", "", 1, "Ponyta is a horse Pokémon known for its speed and fiery mane.");
        addPokemon(db, "Rapidash", "Fire", "", 1, "Rapidash is the evolved form of Ponyta, known for its elegance.");
        addPokemon(db, "Slowpoke", "Water", "Psychic", 1, "Slowpoke is a slow-moving Pokémon known for its laid-back nature.");
        addPokemon(db, "Slowbro", "Water", "Psychic", 1, "Slowbro is the evolved form of Slowpoke, known for its strong tail.");
        addPokemon(db, "Magnemite", "Electric", "Steel", 1, "Magnemite is a magnetic Pokémon that can levitate.");
        addPokemon(db, "Magneton", "Electric", "Steel", 1, "Magneton is the evolved form of Magnemite, known for its three units.");
        addPokemon(db, "Farfetch'd", "Normal", "Flying", 1, "Farfetch'd is a duck Pokémon known for carrying a leek.");
        addPokemon(db, "Doduo", "Normal", "Flying", 1, "Doduo is a bird Pokémon with two heads, known for its speed.");
        addPokemon(db, "Dodrio", "Normal", "Flying", 1, "Dodrio is the evolved form of Doduo, known for its three heads.");
        addPokemon(db, "Seel", "Water", "", 1, "Seel is a seal Pokémon known for its swimming abilities.");
        addPokemon(db, "Dewgong", "Water", "Ice", 1, "Dewgong is the evolved form of Seel, known for its gracefulness.");
        addPokemon(db, "Grimer", "Poison", "", 1, "Grimer is a sludge Pokémon that can be found in sewers.");
        addPokemon(db, "Muk", "Poison", "", 1, "Muk is the evolved form of Grimer, known for its toxic sludge.");
        addPokemon(db, "Shellder", "Water", "Ice", 1, "Shellder is a clam Pokémon known for its hard shell.");
        addPokemon(db, "Cloyster", "Water", "Ice", 1, "Cloyster is the evolved form of Shellder, known for its defensive abilities.");
        addPokemon(db, "Gastly", "Ghost", "Poison", 1, "Gastly is a ghost Pokémon that is made of gas.");
        addPokemon(db, "Haunter", "Ghost", "Poison", 1, "Haunter is the evolved form of Gastly, known for its floating hands.");
        addPokemon(db, "Gengar", "Ghost", "Poison", 1, "Gengar is the final form of Gastly, known for its mischievous nature.");
        addPokemon(db, "Onix", "Rock", "Ground", 1, "Onix is a rock snake Pokémon known for its size and strength.");
        addPokemon(db, "Drowzee", "Psychic", "", 1, "Drowzee is a Pokémon known for its ability to induce sleep.");
        addPokemon(db, "Hypno", "Psychic", "", 1, "Hypno is the evolved form of Drowzee, known for its hypnotic abilities.");
        addPokemon(db, "Krabby", "Water", "", 1, "Krabby is a small crab Pokémon known for its pincers.");
        addPokemon(db, "Kingler", "Water", "", 1, "Kingler is the evolved form of Krabby, known for its massive claw.");
        addPokemon(db, "Voltorb", "Electric", "", 1, "Voltorb is a ball-shaped Pokémon that resembles a Poké Ball.");
        addPokemon(db, "Electrode", "Electric", "", 1, "Electrode is the evolved form of Voltorb, known for its speed.");
        addPokemon(db, "Exeggcute", "Grass", "Psychic", 1, "Exeggcute is a group of eggs that are known for their psychic powers.");
        addPokemon(db, "Exeggutor", "Grass", "Psychic", 1, "Exeggutor is the evolved form of Exeggcute, known for its three heads.");
        addPokemon(db, "Cubone", "Ground", "", 1, "Cubone is a small Pokémon known for wearing its mother's skull.");
        addPokemon(db, "Marowak", "Ground", "", 1, "Marowak is the evolved form of Cubone, known for its bone club.");
        addPokemon(db, "Hitmonlee", "Fighting", "", 1, "Hitmonlee is a fighting Pokémon known for its powerful legs.");
        addPokemon(db, "Hitmonchan", "Fighting", "", 1, "Hitmonchan is a fighting Pokémon known for its boxing skills.");
        addPokemon(db, "Lickitung", "Normal", "", 1, "Lickitung is a Pokémon known for its long tongue.");
        addPokemon(db, "Koffing", "Poison", "", 1, "Koffing is a Pokémon filled with toxic gas.");
        addPokemon(db, "Weezing", "Poison", "", 1, "Weezing is the evolved form of Koffing, known for its two heads.");
        addPokemon(db, "Rhyhorn", "Ground", "Rock", 1, "Rhyhorn is a horned Pokémon known for its strength.");
        addPokemon(db, "Rhydon", "Ground", "Rock", 1, "Rhydon is the evolved form of Rhyhorn, known for its power.");
        addPokemon(db, "Chansey", "Normal", "", 1, "Chansey is a Pokémon known for its healing abilities.");
        addPokemon(db, "Tangela", "Grass", "", 1, "Tangela is a grass Pokémon covered in vines.");
        addPokemon(db, "Kangaskhan", "Normal", "", 1, "Kangaskhan is a kangaroo Pokémon known for carrying its baby in a pouch.");
        addPokemon(db, "Horsea", "Water", "", 1, "Horsea is a small seahorse Pokémon known for its swimming abilities.");
        addPokemon(db, "Seadra", "Water", "", 1, "Seadra is the evolved form of Horsea, known for its spines.");
        addPokemon(db, "Goldeen", "Water", "", 1, "Goldeen is a fish Pokémon known for its elegant fins.");
        addPokemon(db, "Seaking", "Water", "", 1, "Seaking is the evolved form of Goldeen, known for its large horn.");
        addPokemon(db, "Staryu", "Water", "", 1, "Staryu is a starfish Pokémon known for its glowing core.");
        addPokemon(db, "Starmie", "Water", "Psychic", 1, "Starmie is the evolved form of Staryu, known for its speed.");
        addPokemon(db, "Mr. Mime", "Psychic", "Fairy", 1, "Mr. Mime is a Pokémon known for its barrier techniques.");
        addPokemon(db, "Scyther", "Bug", "Flying", 1, "Scyther is a mantis Pokémon known for its speed and scythes.");
        addPokemon(db, "Jynx", "Ice", "Psychic", 1, "Jynx is a Pokémon known for its singing and ice powers.");
        addPokemon(db, "Electabuzz", "Electric", "", 1, "Electabuzz is an electric Pokémon known for its powerful attacks.");
        addPokemon(db, "Magmar", "Fire", "", 1, "Magmar is a fire Pokémon known for its fiery body.");
        addPokemon(db, "Pinsir", "Bug", "", 1, "Pinsir is a bug Pokémon known for its pincers.");
        addPokemon(db, "Tauros", "Normal", "", 1, "Tauros is a bull Pokémon known for its strength.");
        addPokemon(db, "Magikarp", "Water", "", 1, "Magikarp is a fish Pokémon known for its poor swimming ability.");
        addPokemon(db, "Gyarados", "Water", "Flying", 1, "Gyarados is the evolved form of Magikarp, known for its ferocity.");
        addPokemon(db, "Lapras", "Water", "Ice", 1, "Lapras is a Pokémon known for its ability to transport people.");
        addPokemon(db, "Ditto", "Normal", "", 1, "Ditto is a shape-shifting Pokémon known for its ability to imitate others.");
        addPokemon(db, "Eevee", "Normal", "", 1, "Eevee is known for its multiple evolutions.");
        addPokemon(db, "Vaporeon", "Water", "", 1, "Vaporeon is one of the possible evolutions of Eevee.");
        addPokemon(db, "Jolteon", "Electric", "", 1, "Jolteon is one of the possible evolutions of Eevee.");
        addPokemon(db, "Flareon", "Fire", "", 1, "Flareon is one of the possible evolutions of Eevee.");
        addPokemon(db, "Porygon", "Normal", "", 1, "Porygon is a digital Pokémon known for its adaptability.");
        addPokemon(db, "Omanyte", "Rock", "Water", 1, "Omanyte is a fossil Pokémon that is known for its shell.");
        addPokemon(db, "Omastar", "Rock", "Water", 1, "Omastar is the evolved form of Omanyte, known for its tentacles.");
        addPokemon(db, "Kabuto", "Rock", "Water", 1, "Kabuto is a fossil Pokémon that resembles a small crab.");
        addPokemon(db, "Kabutops", "Rock", "Water", 1, "Kabutops is the evolved form of Kabuto, known for its scythe-like arms.");
        addPokemon(db, "Aerodactyl", "Rock", "Flying", 1, "Aerodactyl is a fossil Pokémon known for its speed.");
        addPokemon(db, "Snorlax", "Normal", "", 1, "Snorlax is a Pokémon known for its huge size and slothful behavior.");
        addPokemon(db, "Articuno", "Ice", "Flying", 1, "Articuno is a legendary Pokémon known for its ice powers.");
        addPokemon(db, "Zapdos", "Electric", "Flying", 1, "Zapdos is a legendary Pokémon known for its electric powers.");
        addPokemon(db, "Moltres", "Fire", "Flying", 1, "Moltres is a legendary Pokémon known for its fiery wings.");
        addPokemon(db, "Dratini", "Dragon", "", 1, "Dratini is a dragon Pokémon known for its gentle nature.");
        addPokemon(db, "Dragonair", "Dragon", "", 1, "Dragonair is the evolved form of Dratini, known for its elegance.");
        addPokemon(db, "Dragonite", "Dragon", "", 1, "Dragonite is the final form of Dratini, known for its power.");
        addPokemon(db, "Mewtwo", "Psychic", "", 1, "Mewtwo is a legendary Pokémon known for its incredible psychic abilities.");
        addPokemon(db, "Mew", "Psychic", "Fairy", 1, "Mew is a mythical Pokémon known for its ability to learn any move.");
        //GEN 2
        addPokemon(db, "Chikorita", "Grass", "", 2, "Chikorita is a Grass-type starter Pokémon known for its gentle nature.");
        addPokemon(db, "Bayleef", "Grass", "", 2, "Bayleef is the evolved form of Chikorita, known for its soothing aroma.");
        addPokemon(db, "Meganium", "Grass", "", 2, "Meganium is the final form of Chikorita, with healing abilities.");
        addPokemon(db, "Cyndaquil", "Fire", "", 2, "Cyndaquil is a Fire-type starter Pokémon known for its flame on its back.");
        addPokemon(db, "Quilava", "Fire", "", 2, "Quilava is the evolved form of Cyndaquil, with greater control over its flames.");
        addPokemon(db, "Typhlosion", "Fire", "", 2, "Typhlosion is the final form of Cyndaquil, known for its explosive power.");
        addPokemon(db, "Totodile", "Water", "", 2, "Totodile is a Water-type starter Pokémon known for its lively personality.");
        addPokemon(db, "Croconaw", "Water", "", 2, "Croconaw is the evolved form of Totodile, with powerful jaws.");
        addPokemon(db, "Feraligatr", "Water", "", 2, "Feraligatr is the final form of Totodile, known for its strength and aggression.");
        addPokemon(db, "Sentret", "Normal", "", 2, "Sentret is a scout Pokémon known for its vigilance.");
        addPokemon(db, "Furret", "Normal", "", 2, "Furret is the evolved form of Sentret, known for its speed and agility.");
        addPokemon(db, "Hoothoot", "Normal", "Flying", 2, "Hoothoot is an owl Pokémon that can sense time precisely.");
        addPokemon(db, "Noctowl", "Normal", "Flying", 2, "Noctowl is the evolved form of Hoothoot, known for its keen eyesight.");
        addPokemon(db, "Ledyba", "Bug", "Flying", 2, "Ledyba is a Bug-type Pokémon known for its gentle behavior in groups.");
        addPokemon(db, "Ledian", "Bug", "Flying", 2, "Ledian is the evolved form of Ledyba, known for its teamwork.");
        addPokemon(db, "Spinarak", "Bug", "Poison", 2, "Spinarak is a spider Pokémon known for its sticky webs.");
        addPokemon(db, "Ariados", "Bug", "Poison", 2, "Ariados is the evolved form of Spinarak, known for its hunting skills.");
        addPokemon(db, "Crobat", "Poison", "Flying", 2, "Crobat is the evolved form of Golbat, known for its speed in flight.");
        addPokemon(db, "Chinchou", "Water", "Electric", 2, "Chinchou is a deep-sea Pokémon known for its bioluminescent lights.");
        addPokemon(db, "Lanturn", "Water", "Electric", 2, "Lanturn is the evolved form of Chinchou, known for lighting up the ocean depths.");
        addPokemon(db, "Pichu", "Electric", "", 2, "Pichu is a baby Pokémon that stores electricity in its cheeks.");
        addPokemon(db, "Cleffa", "Fairy", "", 2, "Cleffa is a baby Pokémon known for its starry origin.");
        addPokemon(db, "Igglybuff", "Normal", "Fairy", 2, "Igglybuff is a baby Pokémon that sings to express itself.");
        addPokemon(db, "Togepi", "Fairy", "", 2, "Togepi is known for bringing good fortune to its trainer.");
        addPokemon(db, "Togetic", "Fairy", "Flying", 2, "Togetic is the evolved form of Togepi, known for its happy disposition.");
        addPokemon(db, "Natu", "Psychic", "Flying", 2, "Natu is a small bird Pokémon known for its mystical abilities.");
        addPokemon(db, "Xatu", "Psychic", "Flying", 2, "Xatu is the evolved form of Natu, known for its foresight.");
        addPokemon(db, "Mareep", "Electric", "", 2, "Mareep is a woolly Electric-type Pokémon that generates static.");
        addPokemon(db, "Flaaffy", "Electric", "", 2, "Flaaffy is the evolved form of Mareep, with soft, insulating fur.");
        addPokemon(db, "Ampharos", "Electric", "", 2, "Ampharos is the final form of Mareep, known for its bright light.");
        addPokemon(db, "Bellossom", "Grass", "", 2, "Bellossom is the evolved form of Gloom, known for its beautiful petals.");
        addPokemon(db, "Marill", "Water", "Fairy", 2, "Marill is known for its playful and buoyant nature.");
        addPokemon(db, "Azumarill", "Water", "Fairy", 2, "Azumarill is the evolved form of Marill, known for its water agility.");
        addPokemon(db, "Sudowoodo", "Rock", "", 2, "Sudowoodo is a Pokémon that mimics trees to avoid enemies.");
        addPokemon(db, "Politoed", "Water", "", 2, "Politoed is the evolved form of Poliwhirl, known for its calming croaks.");
        addPokemon(db, "Hoppip", "Grass", "Flying", 2, "Hoppip is a Grass-type Pokémon that floats with the wind.");
        addPokemon(db, "Skiploom", "Grass", "Flying", 2, "Skiploom is the evolved form of Hoppip, known for floating in the air.");
        addPokemon(db, "Jumpluff", "Grass", "Flying", 2, "Jumpluff is the final form of Hoppip, known for its spores.");
        addPokemon(db, "Aipom", "Normal", "", 2, "Aipom is a playful Pokémon known for its dexterous tail.");
        addPokemon(db, "Sunkern", "Grass", "", 2, "Sunkern is a seed Pokémon that subsists on sunlight.");
        addPokemon(db, "Sunflora", "Grass", "", 2, "Sunflora is the evolved form of Sunkern, known for its bright petals.");
        addPokemon(db, "Yanma", "Bug", "Flying", 2, "Yanma is a dragonfly Pokémon known for its agility.");
        addPokemon(db, "Wooper", "Water", "Ground", 2, "Wooper is a small, water-dwelling Pokémon with a friendly demeanor.");
        addPokemon(db, "Quagsire", "Water", "Ground", 2, "Quagsire is the evolved form of Wooper, known for its laid-back nature.");
        addPokemon(db, "Espeon", "Psychic", "", 2, "Espeon is one of Eevee's evolutions, known for its psychic abilities.");
        addPokemon(db, "Umbreon", "Dark", "", 2, "Umbreon is one of Eevee's evolutions, known for its nocturnal habits.");
        addPokemon(db, "Murkrow", "Dark", "Flying", 2, "Murkrow is a mischievous bird Pokémon.");
        addPokemon(db, "Slowking", "Water", "Psychic", 2, "Slowking is the evolved form of Slowpoke, known for its wisdom.");
        addPokemon(db, "Misdreavus", "Ghost", "", 2, "Misdreavus is a ghost Pokémon known for its eerie cries.");
        addPokemon(db, "Unown", "Psychic", "", 2, "Unown is a mysterious Pokémon shaped like letters.");
        addPokemon(db, "Wobbuffet", "Psychic", "", 2, "Wobbuffet is known for its counter-attack ability.");
        addPokemon(db, "Girafarig", "Normal", "Psychic", 2, "Girafarig is a Pokémon with a dual nature.");
        addPokemon(db, "Pineco", "Bug", "", 2, "Pineco is a Pokémon that hangs from trees, waiting to drop.");
        addPokemon(db, "Forretress", "Bug", "Steel", 2, "Forretress is the evolved form of Pineco, known for its sturdy shell.");
        addPokemon(db, "Dunsparce", "Normal", "", 2, "Dunsparce is a rare Pokémon known for burrowing underground.");
        addPokemon(db, "Gligar", "Ground", "Flying", 2, "Gligar is a gliding Pokémon with sharp claws.");
        addPokemon(db, "Steelix", "Steel", "Ground", 2, "Steelix is the evolved form of Onix, known for its durability.");
        addPokemon(db, "Snubbull", "Fairy", "", 2, "Snubbull is a Fairy-type Pokémon known for its grumpy face.");
        addPokemon(db, "Granbull", "Fairy", "", 2, "Granbull is the evolved form of Snubbull, known for its strength.");
        addPokemon(db, "Qwilfish", "Water", "Poison", 2, "Qwilfish is a Pokémon known for inflating its body as a defense.");
        addPokemon(db, "Scizor", "Bug", "Steel", 2, "Scizor is the evolved form of Scyther, known for its cutting claws.");
        addPokemon(db, "Shuckle", "Bug", "Rock", 2, "Shuckle is a slow but incredibly durable Pokémon.");
        addPokemon(db, "Heracross", "Bug", "Fighting", 2, "Heracross is a beetle Pokémon with impressive strength.");
        addPokemon(db, "Sneasel", "Dark", "Ice", 2, "Sneasel is a cunning and quick Pokémon.");
        addPokemon(db, "Teddiursa", "Normal", "", 2, "Teddiursa is a bear Pokémon known for its love of sweets.");
        addPokemon(db, "Ursaring", "Normal", "", 2, "Ursaring is the evolved form of Teddiursa, known for its strength.");
        addPokemon(db, "Slugma", "Fire", "", 2, "Slugma is a lava Pokémon that constantly melts.");
        addPokemon(db, "Magcargo", "Fire", "Rock", 2, "Magcargo is the evolved form of Slugma, known for its molten body.");
        addPokemon(db, "Swinub", "Ice", "Ground", 2, "Swinub is a small Pokémon that burrows in snow.");
        addPokemon(db, "Piloswine", "Ice", "Ground", 2, "Piloswine is the evolved form of Swinub, with long, coarse fur.");
        addPokemon(db, "Corsola", "Water", "Rock", 2, "Corsola is a coral Pokémon known for regenerating its branches.");
        addPokemon(db, "Remoraid", "Water", "", 2, "Remoraid is a small, fish-like Pokémon.");
        addPokemon(db, "Octillery", "Water", "", 2, "Octillery is the evolved form of Remoraid, known for its suction cups.");
        addPokemon(db, "Delibird", "Ice", "Flying", 2, "Delibird is a Pokémon known for carrying gifts.");
        addPokemon(db, "Mantine", "Water", "Flying", 2, "Mantine is a gentle Pokémon that glides underwater.");
        addPokemon(db, "Skarmory", "Steel", "Flying", 2, "Skarmory is a bird Pokémon with metallic feathers.");
        addPokemon(db, "Houndour", "Dark", "Fire", 2, "Houndour is a dark Pokémon with a strong sense of smell.");
        addPokemon(db, "Houndoom", "Dark", "Fire", 2, "Houndoom is the evolved form of Houndour, known for its intimidating appearance.");
        addPokemon(db, "Kingdra", "Water", "Dragon", 2, "Kingdra is the evolved form of Seadra, known for creating whirlpools.");
        addPokemon(db, "Phanpy", "Ground", "", 2, "Phanpy is a small elephant Pokémon known for its strength.");
        addPokemon(db, "Donphan", "Ground", "", 2, "Donphan is the evolved form of Phanpy, with tough armor.");
        addPokemon(db, "Porygon2", "Normal", "", 2, "Porygon2 is the evolved form of Porygon, with upgraded software.");
        addPokemon(db, "Stantler", "Normal", "", 2, "Stantler is a deer-like Pokémon known for its hypnotic antlers.");
        addPokemon(db, "Smeargle", "Normal", "", 2, "Smeargle is an artist Pokémon that can copy moves.");
        addPokemon(db, "Tyrogue", "Fighting", "", 2, "Tyrogue is a small Fighting-type Pokémon that loves to train.");
        addPokemon(db, "Hitmontop", "Fighting", "", 2, "Hitmontop is the evolved form of Tyrogue, known for spinning kicks.");
        addPokemon(db, "Smoochum", "Ice", "Psychic", 2, "Smoochum is a baby Pokémon known for its kisses.");
        addPokemon(db, "Elekid", "Electric", "", 2, "Elekid is a baby Pokémon known for storing electricity.");
        addPokemon(db, "Magby", "Fire", "", 2, "Magby is a baby Pokémon with a fiery disposition.");
        addPokemon(db, "Miltank", "Normal", "", 2, "Miltank is known for its nutritious milk.");
        addPokemon(db, "Blissey", "Normal", "", 2, "Blissey is the evolved form of Chansey, known for its caring nature.");
        addPokemon(db, "Raikou", "Electric", "", 2, "Raikou is a Legendary Pokémon embodying the power of lightning.");
        addPokemon(db, "Entei", "Fire", "", 2, "Entei is a Legendary Pokémon embodying the power of fire.");
        addPokemon(db, "Suicune", "Water", "", 2, "Suicune is a Legendary Pokémon embodying the power of water.");
        addPokemon(db, "Larvitar", "Rock", "Ground", 2, "Larvitar is a small Rock-type Pokémon known for its resilience.");
        addPokemon(db, "Pupitar", "Rock", "Ground", 2, "Pupitar is the evolved form of Larvitar, known for its sturdy shell.");
        addPokemon(db, "Tyranitar", "Rock", "Dark", 2, "Tyranitar is the final form of Larvitar, known for its immense strength.");
        addPokemon(db, "Lugia", "Psychic", "Flying", 2, "Lugia is a Legendary Pokémon known as the guardian of the seas.");
        addPokemon(db, "Ho-Oh", "Fire", "Flying", 2, "Ho-Oh is a Legendary Pokémon known as the guardian of the skies.");
        addPokemon(db, "Celebi", "Psychic", "Grass", 2, "Celebi is a Mythical Pokémon known for its ability to travel through time.");
        //GEN 3
        addPokemon(db, "Treecko", "Grass", "", 3, "Treecko is a small, wood gecko Pokémon known for its agility.");
        addPokemon(db, "Grovyle", "Grass", "", 3, "Grovyle is the evolved form of Treecko, skilled at moving through trees.");
        addPokemon(db, "Sceptile", "Grass", "", 3, "Sceptile is the final form of Treecko, known for its leaf blades.");
        addPokemon(db, "Torchic", "Fire", "", 3, "Torchic is a small, chick Pokémon with a fiery spirit.");
        addPokemon(db, "Combusken", "Fire", "Fighting", 3, "Combusken is the evolved form of Torchic, known for its fiery kicks.");
        addPokemon(db, "Blaziken", "Fire", "Fighting", 3, "Blaziken is the final form of Torchic, famous for its powerful moves.");
        addPokemon(db, "Mudkip", "Water", "", 3, "Mudkip is a water Pokémon known for its strong swimming ability.");
        addPokemon(db, "Marshtomp", "Water", "Ground", 3, "Marshtomp is the evolved form of Mudkip, suited for land and water.");
        addPokemon(db, "Swampert", "Water", "Ground", 3, "Swampert is the final form of Mudkip, known for its great strength.");
        addPokemon(db, "Poochyena", "Dark", "", 3, "Poochyena is a small, hyena-like Pokémon.");
        addPokemon(db, "Mightyena", "Dark", "", 3, "Mightyena is the evolved form of Poochyena, known for its fierce loyalty.");
        addPokemon(db, "Zigzagoon", "Normal", "", 3, "Zigzagoon is a small Pokémon with a curious nature.");
        addPokemon(db, "Linoone", "Normal", "", 3, "Linoone is the evolved form of Zigzagoon, known for its quick movements.");
        addPokemon(db, "Wurmple", "Bug", "", 3, "Wurmple is a small, caterpillar-like Pokémon.");
        addPokemon(db, "Silcoon", "Bug", "", 3, "Silcoon is a cocoon Pokémon that evolves from Wurmple.");
        addPokemon(db, "Beautifly", "Bug", "Flying", 3, "Beautifly is the evolved form of Silcoon, known for its beauty.");
        addPokemon(db, "Cascoon", "Bug", "", 3, "Cascoon is another form of cocoon Pokémon that evolves from Wurmple.");
        addPokemon(db, "Dustox", "Bug", "Poison", 3, "Dustox is the evolved form of Cascoon, known for its toxic scales.");
        addPokemon(db, "Lotad", "Water", "Grass", 3, "Lotad is a small Pokémon that resembles a lilypad.");
        addPokemon(db, "Lombre", "Water", "Grass", 3, "Lombre is the evolved form of Lotad, known for its playful nature.");
        addPokemon(db, "Ludicolo", "Water", "Grass", 3, "Ludicolo is the final form of Lotad, known for its dance-like movements.");
        addPokemon(db, "Seedot", "Grass", "", 3, "Seedot is a small acorn-like Pokémon.");
        addPokemon(db, "Nuzleaf", "Grass", "Dark", 3, "Nuzleaf is the evolved form of Seedot, known for its trickster nature.");
        addPokemon(db, "Shiftry", "Grass", "Dark", 3, "Shiftry is the final form of Seedot, known for its leaf fans.");
        addPokemon(db, "Taillow", "Normal", "Flying", 3, "Taillow is a small bird Pokémon known for its bravery.");
        addPokemon(db, "Swellow", "Normal", "Flying", 3, "Swellow is the evolved form of Taillow, known for its speed.");
        addPokemon(db, "Wingull", "Water", "Flying", 3, "Wingull is a seagull Pokémon that enjoys the sea breeze.");
        addPokemon(db, "Pelipper", "Water", "Flying", 3, "Pelipper is the evolved form of Wingull, known for its large beak.");
        addPokemon(db, "Ralts", "Psychic", "Fairy", 3, "Ralts is a small Pokémon that senses emotions.");
        addPokemon(db, "Kirlia", "Psychic", "Fairy", 3, "Kirlia is the evolved form of Ralts, known for its graceful moves.");
        addPokemon(db, "Gardevoir", "Psychic", "Fairy", 3, "Gardevoir is the final form of Ralts, known for protecting its trainer.");
        addPokemon(db, "Surskit", "Bug", "Water", 3, "Surskit is a small Pokémon that skims across water.");
        addPokemon(db, "Masquerain", "Bug", "Flying", 3, "Masquerain is the evolved form of Surskit, known for its intimidating eyes.");
        addPokemon(db, "Shroomish", "Grass", "", 3, "Shroomish is a mushroom Pokémon that releases spores.");
        addPokemon(db, "Breloom", "Grass", "Fighting", 3, "Breloom is the evolved form of Shroomish, known for its strong punches.");
        addPokemon(db, "Slakoth", "Normal", "", 3, "Slakoth is a lazy Pokémon that spends most of its time resting.");
        addPokemon(db, "Vigoroth", "Normal", "", 3, "Vigoroth is the evolved form of Slakoth, known for its energetic nature.");
        addPokemon(db, "Slaking", "Normal", "", 3, "Slaking is the final form of Slakoth, known for its immense strength.");
        addPokemon(db, "Nincada", "Bug", "Ground", 3, "Nincada is a small Pokémon that burrows underground.");
        addPokemon(db, "Ninjask", "Bug", "Flying", 3, "Ninjask is the evolved form of Nincada, known for its incredible speed.");
        addPokemon(db, "Shedinja", "Bug", "Ghost", 3, "Shedinja is a unique Pokémon that evolves from Nincada under certain conditions.");
        addPokemon(db, "Whismur", "Normal", "", 3, "Whismur is a small Pokémon known for its loud cries.");
        addPokemon(db, "Loudred", "Normal", "", 3, "Loudred is the evolved form of Whismur, known for its powerful voice.");
        addPokemon(db, "Exploud", "Normal", "", 3, "Exploud is the final form of Whismur, known for its earth-shaking roars.");
        addPokemon(db, "Makuhita", "Fighting", "", 3, "Makuhita is a tough Pokémon that trains hard.");
        addPokemon(db, "Hariyama", "Fighting", "", 3, "Hariyama is the evolved form of Makuhita, known for its massive hands.");
        addPokemon(db, "Azurill", "Normal", "Fairy", 3, "Azurill is a small Pokémon known for its bouncy tail.");
        addPokemon(db, "Nosepass", "Rock", "", 3, "Nosepass is a compass Pokémon that points north.");
        addPokemon(db, "Skitty", "Normal", "", 3, "Skitty is a playful cat Pokémon.");
        addPokemon(db, "Delcatty", "Normal", "", 3, "Delcatty is the evolved form of Skitty, known for its relaxed nature.");
        addPokemon(db, "Sableye", "Dark", "Ghost", 3, "Sableye is a mysterious Pokémon known for its jewel-like eyes.");
        addPokemon(db, "Mawile", "Steel", "Fairy", 3, "Mawile is a Pokémon known for its deceptive appearance.");
        addPokemon(db, "Aron", "Steel", "Rock", 3, "Aron is a small Pokémon that eats iron.");
        addPokemon(db, "Lairon", "Steel", "Rock", 3, "Lairon is the evolved form of Aron, known for its tough armor.");
        addPokemon(db, "Aggron", "Steel", "Rock", 3, "Aggron is the final form of Aron, known for its immense defense.");
        addPokemon(db, "Meditite", "Fighting", "Psychic", 3, "Meditite is a meditative Pokémon.");
        addPokemon(db, "Medicham", "Fighting", "Psychic", 3, "Medicham is the evolved form of Meditite, known for its powerful strikes.");
        addPokemon(db, "Electrike", "Electric", "", 3, "Electrike is a small, dog-like Pokémon that generates electricity.");
        addPokemon(db, "Manectric", "Electric", "", 3, "Manectric is the evolved form of Electrike, known for its speed.");
        addPokemon(db, "Plusle", "Electric", "", 3, "Plusle is a cheerful Pokémon that creates sparks to cheer on friends.");
        addPokemon(db, "Minun", "Electric", "", 3, "Minun is similar to Plusle, often seen cheering on its partners.");
        addPokemon(db, "Volbeat", "Bug", "", 3, "Volbeat is a firefly Pokémon that uses its glow to communicate.");
        addPokemon(db, "Illumise", "Bug", "", 3, "Illumise is often seen with Volbeat, known for its dance-like movements.");
        addPokemon(db, "Roselia", "Grass", "Poison", 3, "Roselia is a rose Pokémon known for its beautiful flowers and toxic thorns.");
        addPokemon(db, "Gulpin", "Poison", "", 3, "Gulpin is a stomach Pokémon with a voracious appetite.");
        addPokemon(db, "Swalot", "Poison", "", 3, "Swalot is the evolved form of Gulpin, known for swallowing anything whole.");
        addPokemon(db, "Carvanha", "Water", "Dark", 3, "Carvanha is a fierce fish Pokémon with sharp teeth.");
        addPokemon(db, "Sharpedo", "Water", "Dark", 3, "Sharpedo is the evolved form of Carvanha, known as the 'bully of the sea.'");
        addPokemon(db, "Wailmer", "Water", "", 3, "Wailmer is a whale Pokémon known for its playful spouts.");
        addPokemon(db, "Wailord", "Water", "", 3, "Wailord is the evolved form of Wailmer, known as the largest Pokémon.");
        addPokemon(db, "Numel", "Fire", "Ground", 3, "Numel is a slow but reliable Pokémon, storing magma in its hump.");
        addPokemon(db, "Camerupt", "Fire", "Ground", 3, "Camerupt is the evolved form of Numel, known for its volcanic eruptions.");
        addPokemon(db, "Torkoal", "Fire", "", 3, "Torkoal is a turtle Pokémon that releases smoke when threatened.");
        addPokemon(db, "Spoink", "Psychic", "", 3, "Spoink is a spring-like Pokémon that bounces to keep its heart beating.");
        addPokemon(db, "Grumpig", "Psychic", "", 3, "Grumpig is the evolved form of Spoink, known for its hypnotic dance.");
        addPokemon(db, "Spinda", "Normal", "", 3, "Spinda is a dizzy Pokémon with a unique spot pattern on each individual.");
        addPokemon(db, "Trapinch", "Ground", "", 3, "Trapinch is an ant-lion Pokémon that digs traps in the sand.");
        addPokemon(db, "Vibrava", "Ground", "Dragon", 3, "Vibrava is the evolved form of Trapinch, known for its vibrating wings.");
        addPokemon(db, "Flygon", "Ground", "Dragon", 3, "Flygon is the final form of Trapinch, known as the 'desert spirit.'");
        addPokemon(db, "Cacnea", "Grass", "", 3, "Cacnea is a cactus Pokémon found in dry regions.");
        addPokemon(db, "Cacturne", "Grass", "Dark", 3, "Cacturne is the evolved form of Cacnea, known for stalking its prey at night.");
        addPokemon(db, "Swablu", "Normal", "Flying", 3, "Swablu is a cotton-winged Pokémon known for its gentle nature.");
        addPokemon(db, "Altaria", "Dragon", "Flying", 3, "Altaria is the evolved form of Swablu, known for its beautiful singing.");
        addPokemon(db, "Zangoose", "Normal", "", 3, "Zangoose is a cat-ferret Pokémon known for its rivalry with Seviper.");
        addPokemon(db, "Seviper", "Poison", "", 3, "Seviper is a snake Pokémon with a long-standing feud with Zangoose.");
        addPokemon(db, "Lunatone", "Rock", "Psychic", 3, "Lunatone is a moon-like Pokémon thought to have come from space.");
        addPokemon(db, "Solrock", "Rock", "Psychic", 3, "Solrock is a sun-like Pokémon that absorbs solar energy.");
        addPokemon(db, "Barboach", "Water", "Ground", 3, "Barboach is a fish Pokémon known for its slippery body.");
        addPokemon(db, "Whiscash", "Water", "Ground", 3, "Whiscash is the evolved form of Barboach, known for causing earthquakes.");
        addPokemon(db, "Corphish", "Water", "", 3, "Corphish is a crustacean Pokémon that adapts to any environment.");
        addPokemon(db, "Crawdaunt", "Water", "Dark", 3, "Crawdaunt is the evolved form of Corphish, known for its rough temperament.");
        addPokemon(db, "Baltoy", "Ground", "Psychic", 3, "Baltoy is a small, clay doll Pokémon that spins to move.");
        addPokemon(db, "Claydol", "Ground", "Psychic", 3, "Claydol is the evolved form of Baltoy, known for its multiple eyes.");
        addPokemon(db, "Lileep", "Rock", "Grass", 3, "Lileep is an ancient Pokémon revived from a fossil.");
        addPokemon(db, "Cradily", "Rock", "Grass", 3, "Cradily is the evolved form of Lileep, known for its grasping tentacles.");
        addPokemon(db, "Anorith", "Rock", "Bug", 3, "Anorith is an ancient Pokémon restored from a fossil.");
        addPokemon(db, "Armaldo", "Rock", "Bug", 3, "Armaldo is the evolved form of Anorith, known for its powerful claws.");
        addPokemon(db, "Feebas", "Water", "", 3, "Feebas is a fish Pokémon with a shabby appearance.");
        addPokemon(db, "Milotic", "Water", "", 3, "Milotic is the evolved form of Feebas, known for its beauty and calming presence.");
        addPokemon(db, "Castform", "Normal", "", 3, "Castform changes its form based on the weather.");
        addPokemon(db, "Kecleon", "Normal", "", 3, "Kecleon is a chameleon Pokémon known for its color-changing ability.");
        addPokemon(db, "Shuppet", "Ghost", "", 3, "Shuppet is a puppet Pokémon that feeds on negative emotions.");
        addPokemon(db, "Banette", "Ghost", "", 3, "Banette is the evolved form of Shuppet, known for its vengeful spirit.");
        addPokemon(db, "Duskull", "Ghost", "", 3, "Duskull is a ghostly Pokémon that loves to frighten people.");
        addPokemon(db, "Dusclops", "Ghost", "", 3, "Dusclops is the evolved form of Duskull, known for its eerie aura.");
        addPokemon(db, "Tropius", "Grass", "Flying", 3, "Tropius is a Pokémon with banana-like fruit on its neck.");
        addPokemon(db, "Chimecho", "Psychic", "", 3, "Chimecho is a wind chime Pokémon known for its soothing sounds.");
        addPokemon(db, "Absol", "Dark", "", 3, "Absol is a disaster Pokémon that appears before natural calamities.");
        addPokemon(db, "Wynaut", "Psychic", "", 3, "Wynaut is a playful Pokémon that evolves into Wobbuffet.");
        addPokemon(db, "Snorunt", "Ice", "", 3, "Snorunt is a cold-climate Pokémon known for bringing good fortune.");
        addPokemon(db, "Glalie", "Ice", "", 3, "Glalie is the evolved form of Snorunt, known for its icy exterior.");
        addPokemon(db, "Spheal", "Ice", "Water", 3, "Spheal is a playful, round Pokémon that rolls around.");
        addPokemon(db, "Sealeo", "Ice", "Water", 3, "Sealeo is the evolved form of Spheal, known for balancing objects.");
        addPokemon(db, "Walrein", "Ice", "Water", 3, "Walrein is the final form of Spheal, known for its tusks.");
        addPokemon(db, "Clamperl", "Water", "", 3, "Clamperl is a clam Pokémon known for its precious pearls.");
        addPokemon(db, "Huntail", "Water", "", 3, "Huntail is an evolved form of Clamperl, found deep in the sea.");
        addPokemon(db, "Gorebyss", "Water", "", 3, "Gorebyss is another evolved form of Clamperl, known for its elegance.");
        addPokemon(db, "Relicanth", "Water", "Rock", 3, "Relicanth is an ancient Pokémon thought to be extinct.");
        addPokemon(db, "Luvdisc", "Water", "", 3, "Luvdisc is a heart-shaped Pokémon known for symbolizing love.");
        addPokemon(db, "Bagon", "Dragon", "", 3, "Bagon dreams of flying and evolves into a powerful dragon.");
        addPokemon(db, "Shelgon", "Dragon", "", 3, "Shelgon is the evolved form of Bagon, with a hard shell.");
        addPokemon(db, "Salamence", "Dragon", "Flying", 3, "Salamence is the final form of Bagon, known for its majestic wings.");
        addPokemon(db, "Beldum", "Steel", "Psychic", 3, "Beldum is a metallic Pokémon that communicates magnetically.");
        addPokemon(db, "Metang", "Steel", "Psychic", 3, "Metang is the evolved form of Beldum, known for its telekinetic powers.");
        addPokemon(db, "Metagross", "Steel", "Psychic", 3, "Metagross is the final form of Beldum, with high intelligence and strength.");
        addPokemon(db, "Regirock", "Rock", "", 3, "Regirock is a golem-like Pokémon made entirely of rock.");
        addPokemon(db, "Regice", "Ice", "", 3, "Regice is a golem-like Pokémon made of ice.");
        addPokemon(db, "Registeel", "Steel", "", 3, "Registeel is a golem-like Pokémon with a metallic body.");
        addPokemon(db, "Latias", "Dragon", "Psychic", 3, "Latias is a legendary Pokémon with a gentle nature.");
        addPokemon(db, "Latios", "Dragon", "Psychic", 3, "Latios is a legendary Pokémon with a strong protective instinct.");
        addPokemon(db, "Kyogre", "Water", "", 3, "Kyogre is a legendary Pokémon that controls the seas.");
        addPokemon(db, "Groudon", "Ground", "", 3, "Groudon is a legendary Pokémon that controls the land.");
        addPokemon(db, "Rayquaza", "Dragon", "Flying", 3, "Rayquaza is a legendary Pokémon that lives in the ozone layer.");
        addPokemon(db, "Jirachi", "Steel", "Psychic", 3, "Jirachi is a wish-granting Pokémon that awakens once every thousand years.");
        addPokemon(db, "Deoxys", "Psychic", "", 3, "Deoxys is an extraterrestrial Pokémon with various forms.");
        //GEN 4
        addPokemon(db, "Turtwig", "Grass", "", 4, "Turtwig is a Grass-type starter Pokémon with a small plant sprouting on its head.");
        addPokemon(db, "Grotle", "Grass", "", 4, "Grotle is the evolved form of Turtwig, known for the bushes growing on its shell.");
        addPokemon(db, "Torterra", "Grass", "Ground", 4, "Torterra is the final form of Turtwig, a giant tortoise with a tree on its shell.");
        addPokemon(db, "Chimchar", "Fire", "", 4, "Chimchar is a Fire-type starter Pokémon resembling a small monkey.");
        addPokemon(db, "Monferno", "Fire", "Fighting", 4, "Monferno is the evolved form of Chimchar, becoming part Fighting-type.");
        addPokemon(db, "Infernape", "Fire", "Fighting", 4, "Infernape is the final form of Chimchar, known for its fiery combat abilities.");
        addPokemon(db, "Piplup", "Water", "", 4, "Piplup is a Water-type starter Pokémon resembling a small penguin.");
        addPokemon(db, "Prinplup", "Water", "", 4, "Prinplup is the evolved form of Piplup, becoming more regal in appearance.");
        addPokemon(db, "Empoleon", "Water", "Steel", 4, "Empoleon is the final form of Piplup, with a Steel-type, emperor-like appearance.");
        addPokemon(db, "Starly", "Normal", "Flying", 4, "Starly is a small bird Pokémon known for its flocking behavior.");
        addPokemon(db, "Staravia", "Normal", "Flying", 4, "Staravia is the evolved form of Starly, often seen in larger flocks.");
        addPokemon(db, "Staraptor", "Normal", "Flying", 4, "Staraptor is the final form of Starly, known for its fierce combat abilities.");
        addPokemon(db, "Bidoof", "Normal", "", 4, "Bidoof is a beaver-like Pokémon, often seen as a common sight in Sinnoh.");
        addPokemon(db, "Bibarel", "Normal", "Water", 4, "Bibarel is the evolved form of Bidoof, gaining a Water-typing.");
        addPokemon(db, "Kricketot", "Bug", "", 4, "Kricketot is a cricket Pokémon that communicates by rubbing its antennae.");
        addPokemon(db, "Kricketune", "Bug", "", 4, "Kricketune is the evolved form of Kricketot, known for its melodic cries.");
        addPokemon(db, "Shinx", "Electric", "", 4, "Shinx is an Electric-type Pokémon with the ability to generate electricity.");
        addPokemon(db, "Luxio", "Electric", "", 4, "Luxio is the evolved form of Shinx, with an intimidating gaze.");
        addPokemon(db, "Luxray", "Electric", "", 4, "Luxray is the final form of Shinx, able to see through objects with its powerful eyes.");
        addPokemon(db, "Budew", "Grass", "Poison", 4, "Budew is a small bud Pokémon that evolves into Roselia.");
        addPokemon(db, "Roserade", "Grass", "Poison", 4, "Roserade is the evolved form of Roselia, known for its elegant flower-like arms.");
        addPokemon(db, "Cranidos", "Rock", "", 4, "Cranidos is a fossil Pokémon known for its powerful headbutts.");
        addPokemon(db, "Rampardos", "Rock", "", 4, "Rampardos is the evolved form of Cranidos, with unmatched physical power.");
        addPokemon(db, "Shieldon", "Rock", "Steel", 4, "Shieldon is a fossil Pokémon known for its shield-like face.");
        addPokemon(db, "Bastiodon", "Rock", "Steel", 4, "Bastiodon is the evolved form of Shieldon, resembling a fortress.");
        addPokemon(db, "Burmy", "Bug", "", 4, "Burmy can change its cloak based on its environment.");
        addPokemon(db, "Wormadam", "Bug", "Grass", 4, "Wormadam is the evolved form of Burmy, with multiple forms depending on its cloak.");
        addPokemon(db, "Mothim", "Bug", "Flying", 4, "Mothim is the male form evolved from Burmy, resembling a moth.");
        addPokemon(db, "Combee", "Bug", "Flying", 4, "Combee is a bee Pokémon, known for its honey-producing abilities.");
        addPokemon(db, "Vespiquen", "Bug", "Flying", 4, "Vespiquen is the evolved form of female Combee, a queen bee Pokémon.");
        addPokemon(db, "Pachirisu", "Electric", "", 4, "Pachirisu is a small squirrel Pokémon known for storing electricity in its cheeks.");
        addPokemon(db, "Buizel", "Water", "", 4, "Buizel is an aquatic Pokémon known for its swimming abilities.");
        addPokemon(db, "Floatzel", "Water", "", 4, "Floatzel is the evolved form of Buizel, capable of high-speed swimming.");
        addPokemon(db, "Cherubi", "Grass", "", 4, "Cherubi is a cherry-like Pokémon with a smaller seed attached.");
        addPokemon(db, "Cherrim", "Grass", "", 4, "Cherrim changes its form based on the weather, blooming under sunlight.");
        addPokemon(db, "Shellos", "Water", "", 4, "Shellos has two forms depending on its habitat in Sinnoh.");
        addPokemon(db, "Gastrodon", "Water", "Ground", 4, "Gastrodon is the evolved form of Shellos, also having two regional forms.");
        addPokemon(db, "Ambipom", "Normal", "", 4, "Ambipom is the evolved form of Aipom, using its tail hands skillfully.");
        addPokemon(db, "Drifloon", "Ghost", "Flying", 4, "Drifloon is a balloon-like Pokémon that floats around carrying small children.");
        addPokemon(db, "Drifblim", "Ghost", "Flying", 4, "Drifblim is the evolved form of Drifloon, known for drifting in the wind.");
        addPokemon(db, "Buneary", "Normal", "", 4, "Buneary is a small rabbit Pokémon, known for its powerful ears.");
        addPokemon(db, "Lopunny", "Normal", "", 4, "Lopunny is the evolved form of Buneary, with an elegant appearance.");
        addPokemon(db, "Mismagius", "Ghost", "", 4, "Mismagius is the evolved form of Misdreavus, known for its incantations.");
        addPokemon(db, "Honchkrow", "Dark", "Flying", 4, "Honchkrow is the evolved form of Murkrow, resembling a mob boss.");
        addPokemon(db, "Glameow", "Normal", "", 4, "Glameow is a feline Pokémon with a graceful, twisted tail.");
        addPokemon(db, "Purugly", "Normal", "", 4, "Purugly is the evolved form of Glameow, with a more aggressive demeanor.");
        addPokemon(db, "Chingling", "Psychic", "", 4, "Chingling is a small bell-like Pokémon with a pleasant ring.");
        addPokemon(db, "Stunky", "Poison", "Dark", 4, "Stunky is a skunk Pokémon known for its foul-smelling spray.");
        addPokemon(db, "Skuntank", "Poison", "Dark", 4, "Skuntank is the evolved form of Stunky, with an even stronger odor.");
        addPokemon(db, "Bronzor", "Steel", "Psychic", 4, "Bronzor is a mysterious disk Pokémon with a reflective surface.");
        addPokemon(db, "Bronzong", "Steel", "Psychic", 4, "Bronzong is the evolved form of Bronzor, known for summoning rain.");
        addPokemon(db, "Bonsly", "Rock", "", 4, "Bonsly is a baby Pokémon that resembles a bonsai tree.");
        addPokemon(db, "Mime Jr.", "Psychic", "Fairy", 4, "Mime Jr. is the baby form of Mr. Mime, mimicking movements.");
        addPokemon(db, "Happiny", "Normal", "", 4, "Happiny is the baby form of Chansey, carrying a stone that resembles an egg.");
        addPokemon(db, "Chatot", "Normal", "Flying", 4, "Chatot is a parrot Pokémon that can mimic human speech.");
        addPokemon(db, "Spiritomb", "Ghost", "Dark", 4, "Spiritomb is a Pokémon said to be formed from 108 spirits.");
        addPokemon(db, "Gible", "Dragon", "Ground", 4, "Gible is a small dragon Pokémon with strong jaws.");
        addPokemon(db, "Gabite", "Dragon", "Ground", 4, "Gabite is the evolved form of Gible, a quick and fierce fighter.");
        addPokemon(db, "Garchomp", "Dragon", "Ground", 4, "Garchomp is the final form of Gible, known for its immense power.");
        addPokemon(db, "Munchlax", "Normal", "", 4, "Munchlax is the baby form of Snorlax, known for its insatiable appetite.");
        addPokemon(db, "Riolu", "Fighting", "", 4, "Riolu is a small jackal Pokémon, sensitive to aura.");
        addPokemon(db, "Lucario", "Fighting", "Steel", 4, "Lucario is the evolved form of Riolu, capable of using aura in combat.");
        addPokemon(db, "Hippopotas", "Ground", "", 4, "Hippopotas is a hippo Pokémon that thrives in deserts.");
        addPokemon(db, "Hippowdon", "Ground", "", 4, "Hippowdon is the evolved form of Hippopotas, known for creating sandstorms.");
        addPokemon(db, "Skorupi", "Poison", "Bug", 4, "Skorupi is a scorpion Pokémon with a deadly grip.");
        addPokemon(db, "Drapion", "Poison", "Dark", 4, "Drapion is the evolved form of Skorupi, a dangerous predator.");
        addPokemon(db, "Croagunk", "Poison", "Fighting", 4, "Croagunk is known for its toxic fingers and sly grin.");
        addPokemon(db, "Toxicroak", "Poison", "Fighting", 4, "Toxicroak is the evolved form of Croagunk, with powerful poison abilities.");
        addPokemon(db, "Carnivine", "Grass", "", 4, "Carnivine is a plant Pokémon that resembles a Venus flytrap.");
        addPokemon(db, "Finneon", "Water", "", 4, "Finneon is a fish Pokémon known for its vibrant fins.");
        addPokemon(db, "Lumineon", "Water", "", 4, "Lumineon is the evolved form of Finneon, resembling a beautiful deep-sea fish.");
        addPokemon(db, "Mantyke", "Water", "Flying", 4, "Mantyke is the baby form of Mantine, a playful ray Pokémon.");
        addPokemon(db, "Snover", "Grass", "Ice", 4, "Snover is a Pokémon that thrives in cold, snowy environments.");
        addPokemon(db, "Abomasnow", "Grass", "Ice", 4, "Abomasnow is the evolved form of Snover, known for creating snowstorms.");
        addPokemon(db, "Weavile", "Dark", "Ice", 4, "Weavile is the evolved form of Sneasel, a cunning ice Pokémon.");
        addPokemon(db, "Magnezone", "Electric", "Steel", 4, "Magnezone is the evolved form of Magneton, with strong magnetic fields.");
        addPokemon(db, "Lickilicky", "Normal", "", 4, "Lickilicky is the evolved form of Lickitung, known for its long tongue.");
        addPokemon(db, "Rhyperior", "Ground", "Rock", 4, "Rhyperior is the evolved form of Rhydon, incredibly durable.");
        addPokemon(db, "Tangrowth", "Grass", "", 4, "Tangrowth is the evolved form of Tangela, with long, powerful vines.");
        addPokemon(db, "Electivire", "Electric", "", 4, "Electivire is the evolved form of Electabuzz, generating powerful electric blasts.");
        addPokemon(db, "Magmortar", "Fire", "", 4, "Magmortar is the evolved form of Magmar, shooting fire from its arms.");
        addPokemon(db, "Togekiss", "Fairy", "Flying", 4, "Togekiss is the evolved form of Togetic, symbolizing happiness.");
        addPokemon(db, "Yanmega", "Bug", "Flying", 4, "Yanmega is the evolved form of Yanma, a large dragonfly Pokémon.");
        addPokemon(db, "Leafeon", "Grass", "", 4, "Leafeon is a Grass-type evolution of Eevee.");
        addPokemon(db, "Glaceon", "Ice", "", 4, "Glaceon is an Ice-type evolution of Eevee.");
        addPokemon(db, "Gliscor", "Ground", "Flying", 4, "Gliscor is the evolved form of Gligar, gliding through the night sky.");
        addPokemon(db, "Mamoswine", "Ice", "Ground", 4, "Mamoswine is the evolved form of Piloswine, large and mammoth-like.");
        addPokemon(db, "Porygon-Z", "Normal", "", 4, "Porygon-Z is an upgraded form of Porygon2, known for its erratic behavior.");
        addPokemon(db, "Gallade", "Psychic", "Fighting", 4, "Gallade is an evolved form of Kirlia with strong blade-like arms.");
        addPokemon(db, "Probopass", "Rock", "Steel", 4, "Probopass is the evolved form of Nosepass, resembling a compass.");
        addPokemon(db, "Dusknoir", "Ghost", "", 4, "Dusknoir is the evolved form of Dusclops, guiding spirits to the afterlife.");
        addPokemon(db, "Froslass", "Ice", "Ghost", 4, "Froslass is the evolved form of female Snorunt, resembling a ghostly maiden.");
        addPokemon(db, "Rotom", "Electric", "Ghost", 4, "Rotom can inhabit various household appliances, changing its type.");
        addPokemon(db, "Uxie", "Psychic", "", 4, "Uxie is one of the lake guardians, symbolizing knowledge.");
        addPokemon(db, "Mesprit", "Psychic", "", 4, "Mesprit is one of the lake guardians, symbolizing emotion.");
        addPokemon(db, "Azelf", "Psychic", "", 4, "Azelf is one of the lake guardians, symbolizing willpower.");
        addPokemon(db, "Dialga", "Steel", "Dragon", 4, "Dialga is a legendary Pokémon that controls time.");
        addPokemon(db, "Palkia", "Water", "Dragon", 4, "Palkia is a legendary Pokémon that controls space.");
        addPokemon(db, "Heatran", "Fire", "Steel", 4, "Heatran dwells within volcanoes, controlling magma.");
        addPokemon(db, "Regigigas", "Normal", "", 4, "Regigigas is a colossal Pokémon said to have moved continents.");
        addPokemon(db, "Giratina", "Ghost", "Dragon", 4, "Giratina is a legendary Pokémon that resides in the Distortion World.");
        addPokemon(db, "Cresselia", "Psychic", "", 4, "Cresselia is a legendary Pokémon that represents the crescent moon.");
        addPokemon(db, "Phione", "Water", "", 4, "Phione is a mythical Pokémon known to drift in warm seas.");
        addPokemon(db, "Manaphy", "Water", "", 4, "Manaphy is a mythical Pokémon that can bond with any Pokémon.");
        addPokemon(db, "Darkrai", "Dark", "", 4, "Darkrai is a mythical Pokémon known to induce nightmares.");
        addPokemon(db, "Shaymin", "Grass", "", 4, "Shaymin is a mythical Pokémon that purifies the air.");
        addPokemon(db, "Arceus", "Normal", "", 4, "Arceus is said to have created the entire Pokémon world.");
        //GEN 5
        addPokemon(db, "Victini", "Psychic", "Fire", 5, "Victini is a mythical Pokémon that brings victory.");
        addPokemon(db, "Snivy", "Grass", "", 5, "Snivy is a Grass-type starter Pokémon that resembles a small snake.");
        addPokemon(db, "Servine", "Grass", "", 5, "Servine is the evolved form of Snivy, known for its elegance.");
        addPokemon(db, "Serperior", "Grass", "", 5, "Serperior is the final form of Snivy, a regal Pokémon with powerful abilities.");
        addPokemon(db, "Tepig", "Fire", "", 5, "Tepig is a Fire-type starter Pokémon resembling a small pig.");
        addPokemon(db, "Pignite", "Fire", "Fighting", 5, "Pignite is the evolved form of Tepig, known for its fighting spirit.");
        addPokemon(db, "Emboar", "Fire", "Fighting", 5, "Emboar is the final form of Tepig, a powerful and bulky Pokémon.");
        addPokemon(db, "Oshawott", "Water", "", 5, "Oshawott is a Water-type starter Pokémon resembling a sea otter.");
        addPokemon(db, "Dewott", "Water", "", 5, "Dewott is the evolved form of Oshawott, a skilled swordsman.");
        addPokemon(db, "Samurott", "Water", "", 5, "Samurott is the final form of Oshawott, commanding the seas.");
        addPokemon(db, "Patrat", "Normal", "", 5, "Patrat is a small rodent Pokémon that is often found in groups.");
        addPokemon(db, "Watchog", "Normal", "", 5, "Watchog is the evolved form of Patrat, known for its vigilant nature.");
        addPokemon(db, "Lillipup", "Normal", "", 5, "Lillipup is a small puppy Pokémon that is very loyal.");
        addPokemon(db, "Herdier", "Normal", "", 5, "Herdier is the evolved form of Lillipup, known for its protective nature.");
        addPokemon(db, "Stoutland", "Normal", "", 5, "Stoutland is the final form of Lillipup, wise and strong.");
        addPokemon(db, "Purrloin", "Dark", "", 5, "Purrloin is a small cat Pokémon known for its cunning nature.");
        addPokemon(db, "Liepard", "Dark", "", 5, "Liepard is the evolved form of Purrloin, sleek and agile.");
        addPokemon(db, "Petilil", "Grass", "", 5, "Petilil is a small flower Pokémon that absorbs sunlight.");
        addPokemon(db, "Lilligant", "Grass", "", 5, "Lilligant is the evolved form of Petilil, known for its elegance.");
        addPokemon(db, "Basculin", "Water", "", 5, "Basculin is a fish Pokémon with two forms, known for its aggression.");
        addPokemon(db, "Sandile", "Ground", "Dark", 5, "Sandile is a crocodile Pokémon that enjoys the sun.");
        addPokemon(db, "Krokorok", "Ground", "Dark", 5, "Krokorok is the evolved form of Sandile, known for its cunning.");
        addPokemon(db, "Krookodile", "Ground", "Dark", 5, "Krookodile is the final form of Sandile, powerful and fierce.");
        addPokemon(db, "Darumaka", "Fire", "", 5, "Darumaka is a small fire Pokémon that resembles a daruma doll.");
        addPokemon(db, "Darmanitan", "Fire", "", 5, "Darmanitan is the evolved form of Darumaka, a fierce warrior.");
        addPokemon(db, "Maractus", "Grass", "", 5, "Maractus is a cactus Pokémon that dances to attract attention.");
        addPokemon(db, "Dwebble", "Bug", "Rock", 5, "Dwebble is a small bug Pokémon that lives in a rock shell.");
        addPokemon(db, "Crustle", "Bug", "Rock", 5, "Crustle is the evolved form of Dwebble, carrying its home on its back.");
        addPokemon(db, "Scraggy", "Dark", "Fighting", 5, "Scraggy is a small lizard Pokémon that wears a baggy skin.");
        addPokemon(db, "Scrafty", "Dark", "Fighting", 5, "Scrafty is the evolved form of Scraggy, known for its street-smart tactics.");
        addPokemon(db, "Sigilyph", "Psychic", "Flying", 5, "Sigilyph is a mysterious Pokémon that protects ancient ruins.");
        addPokemon(db, "Yamask", "Ghost", "", 5, "Yamask is a ghost Pokémon that carries a mask representing its past.");
        addPokemon(db, "Cofagrigus", "Ghost", "", 5, "Cofagrigus is the evolved form of Yamask, resembling a sarcophagus.");
        addPokemon(db, "Tirtouga", "Water", "Rock", 5, "Tirtouga is a turtle Pokémon that lived in ancient times.");
        addPokemon(db, "Carracosta", "Water", "Rock", 5, "Carracosta is the evolved form of Tirtouga, a powerful swimmer.");
        addPokemon(db, "Archen", "Rock", "Flying", 5, "Archen is a fossil Pokémon that can fly despite being ancient.");
        addPokemon(db, "Archeops", "Rock", "Flying", 5, "Archeops is the evolved form of Archen, known for its speed and ferocity.");
        addPokemon(db, "Trubbish", "Poison", "", 5, "Trubbish is a trash bag Pokémon, often found in urban areas.");
        addPokemon(db, "Garbodor", "Poison", "", 5, "Garbodor is the evolved form of Trubbish, a large trash Pokémon.");
        addPokemon(db, "Zorua", "Dark", "", 5, "Zorua is a small fox Pokémon that can transform into others.");
        addPokemon(db, "Zoroark", "Dark", "", 5, "Zoroark is the evolved form of Zorua, a master of illusion.");
        addPokemon(db, "Minccino", "Normal", "", 5, "Minccino is a small chinchilla Pokémon known for its cleanliness.");
        addPokemon(db, "Cinccino", "Normal", "", 5, "Cinccino is the evolved form of Minccino, known for its beautiful fur.");
        addPokemon(db, "Gothita", "Psychic", "", 5, "Gothita is a small Pokémon that can manipulate the feelings of others.");
        addPokemon(db, "Gothorita", "Psychic", "", 5, "Gothorita is the evolved form of Gothita, known for its telepathic abilities.");
        addPokemon(db, "Gothitelle", "Psychic", "", 5, "Gothitelle is the final form of Gothita, powerful and mysterious.");
        addPokemon(db, "Solrock", "Rock", "Psychic", 5, "Solrock is a Pokémon that resembles a sun, radiating energy.");
        addPokemon(db, "Lunatone", "Rock", "Psychic", 5, "Lunatone is a Pokémon that resembles a moon, mysterious and serene.");
        addPokemon(db, "Ducklett", "Water", "Flying", 5, "Ducklett is a small duck Pokémon that loves to swim.");
        addPokemon(db, "Swanna", "Water", "Flying", 5, "Swanna is the evolved form of Ducklett, known for its grace.");
        addPokemon(db, "Vanillite", "Ice", "", 5, "Vanillite is an ice cream Pokémon, resembling a small scoop of ice cream.");
        addPokemon(db, "Vanillish", "Ice", "", 5, "Vanillish is the evolved form of Vanillite, larger and more powerful.");
        addPokemon(db, "Vanilluxe", "Ice", "", 5, "Vanilluxe is the final form of Vanillite, resembling a double scoop ice cream.");
        addPokemon(db, "Deerling", "Normal", "Grass", 5, "Deerling changes appearance with the seasons.");
        addPokemon(db, "Sawsbuck", "Normal", "Grass", 5, "Sawsbuck is the evolved form of Deerling, majestic and seasonal.");
        addPokemon(db, "Emolga", "Electric", "Flying", 5, "Emolga is a small flying squirrel Pokémon known for its agility.");
        addPokemon(db, "Karrablast", "Bug", "", 5, "Karrablast is a bug Pokémon known for its armored body.");
        addPokemon(db, "Escavalier", "Bug", "Steel", 5, "Escavalier is the evolved form of Karrablast, resembling a knight.");
        addPokemon(db, "Foongus", "Grass", "Poison", 5, "Foongus is a mushroom Pokémon that resembles a Poké Ball.");
        addPokemon(db, "Amoonguss", "Grass", "Poison", 5, "Amoonguss is the evolved form of Foongus, known for its deception.");
        addPokemon(db, "Frillish", "Water", "Ghost", 5, "Frillish is a jellyfish Pokémon that drifts through the sea.");
        addPokemon(db, "Jellicent", "Water", "Ghost", 5, "Jellicent is the evolved form of Frillish, elegant and mysterious.");
        addPokemon(db, "Alomomola", "Water", "", 5, "Alomomola is a pink fish Pokémon known for its healing abilities.");
        addPokemon(db, "Sandygast", "Ghost", "Ground", 5, "Sandygast is a sandcastle Pokémon that possesses a spooky essence.");
        addPokemon(db, "Palossand", "Ghost", "Ground", 5, "Palossand is the evolved form of Sandygast, a haunted sandcastle.");
        addPokemon(db, "Stufful", "Normal", "Fighting", 5, "Stufful is a cute bear Pokémon that loves to be cuddled.");
        addPokemon(db, "Bewear", "Normal", "Fighting", 5, "Bewear is the evolved form of Stufful, strong and protective.");
        addPokemon(db, "Bounsweet", "Grass", "", 5, "Bounsweet is a small fruit Pokémon known for its sweet scent.");
        addPokemon(db, "Steenee", "Grass", "", 5, "Steenee is the evolved form of Bounsweet, known for its agility.");
        addPokemon(db, "Tsareena", "Grass", "", 5, "Tsareena is the final form of Bounsweet, a queen among Pokémon.");
        addPokemon(db, "Togekiss", "Fairy", "Flying", 5, "Togekiss is a Pokémon known for bringing happiness.");
        addPokemon(db, "Mimikyu", "Ghost", "Fairy", 5, "Mimikyu is a Pokémon that hides its true form under a rag.");
        addPokemon(db, "Oricorio", "Fire", "Flying", 5, "Oricorio is a dancing Pokémon that can change forms.");
        addPokemon(db, "Cutiefly", "Bug", "Fairy", 5, "Cutiefly is a small fairy Pokémon that loves nectar.");
        addPokemon(db, "Ribombee", "Bug", "Fairy", 5, "Ribombee is the evolved form of Cutiefly, known for its beauty.");
        addPokemon(db, "Lurantis", "Grass", "", 5, "Lurantis is a Pokémon that resembles a beautiful flower.");
        addPokemon(db, "Shiinotic", "Grass", "Fairy", 5, "Shiinotic is a mushroom Pokémon that emits a soothing light.");
        addPokemon(db, "Salandit", "Fire", "Poison", 5, "Salandit is a small lizard Pokémon that can create flames.");
        addPokemon(db, "Salazzle", "Fire", "Poison", 5, "Salazzle is the evolved form of Salandit, a fierce and cunning predator.");
        addPokemon(db, "Stufful", "Normal", "Fighting", 5, "Stufful is a cute bear Pokémon that loves to be cuddled.");
        addPokemon(db, "Bewear", "Normal", "Fighting", 5, "Bewear is the evolved form of Stufful, strong and protective.");
        //GEN 6
        addPokemon(db, "Chespin", "Grass", "", 6, "Chespin is a small spiny Pokémon, a Grass-type starter.");
        addPokemon(db, "Quilladin", "Grass", "", 6, "Quilladin is the evolved form of Chespin, known for its toughness.");
        addPokemon(db, "Chesnaught", "Grass", "Fighting", 6, "Chesnaught is the final form of Chespin, a strong defender.");
        addPokemon(db, "Fennekin", "Fire", "", 6, "Fennekin is a small fox Pokémon, a Fire-type starter.");
        addPokemon(db, "Braixen", "Fire", "", 6, "Braixen is the evolved form of Fennekin, known for its wand.");
        addPokemon(db, "Delphox", "Fire", "Psychic", 6, "Delphox is the final form of Fennekin, a mystical Pokémon.");
        addPokemon(db, "Froakie", "Water", "", 6, "Froakie is a small frog Pokémon, a Water-type starter.");
        addPokemon(db, "Frogadier", "Water", "", 6, "Frogadier is the evolved form of Froakie, agile and swift.");
        addPokemon(db, "Greninja", "Water", "Dark", 6, "Greninja is the final form of Froakie, known for its speed.");
        addPokemon(db, "Bunnelby", "Normal", "", 6, "Bunnelby is a small rabbit Pokémon known for its digging ability.");
        addPokemon(db, "Diggersby", "Normal", "Ground", 6, "Diggersby is the evolved form of Bunnelby, powerful and burly.");
        addPokemon(db, "Fletchling", "Normal", "Flying", 6, "Fletchling is a small bird Pokémon known for its cheerful song.");
        addPokemon(db, "Fletchinder", "Fire", "Flying", 6, "Fletchinder is the evolved form of Fletchling, fiery and fast.");
        addPokemon(db, "TalONflame", "Fire", "Flying", 6, "TalONflame is the final form of Fletchling, fierce and bold.");
        addPokemon(db, "Scatterbug", "Bug", "", 6, "Scatterbug is a small caterpillar Pokémon that evolves into many forms.");
        addPokemon(db, "Spewpa", "Bug", "", 6, "Spewpa is the evolved form of Scatterbug, known for its defense.");
        addPokemon(db, "Vivillon", "Bug", "Flying", 6, "Vivillon is the final form of Scatterbug, known for its beautiful wings.");
        addPokemon(db, "Litleo", "Fire", "Normal", 6, "Litleo is a small lion cub Pokémon that loves to play.");
        addPokemon(db, "Pyroar", "Fire", "Normal", 6, "Pyroar is the evolved form of Litleo, a majestic lion.");
        addPokemon(db, "Flabébé", "Fairy", "", 6, "Flabébé is a small fairy Pokémon that is often found with flowers.");
        addPokemon(db, "Floette", "Fairy", "", 6, "Floette is the evolved form of Flabébé, known for its grace.");
        addPokemon(db, "Florges", "Fairy", "", 6, "Florges is the final form of Flabébé, a regal flower Pokémon.");
        addPokemon(db, "Skiddo", "Grass", "", 6, "Skiddo is a small goat Pokémon that loves to graze.");
        addPokemon(db, "Gogoat", "Grass", "", 6, "Gogoat is the evolved form of Skiddo, strong and dependable.");
        addPokemon(db, "Pancham", "Fighting", "", 6, "Pancham is a small panda Pokémon that loves to play.");
        addPokemon(db, "Pangoro", "Fighting", "Dark", 6, "Pangoro is the evolved form of Pancham, fierce and loyal.");
        addPokemon(db, "Furfrou", "Normal", "", 6, "Furfrou is a poodle Pokémon known for its stylish fur.");
        addPokemon(db, "Espurr", "Psychic", "", 6, "Espurr is a small cat Pokémon with large ears.");
        addPokemon(db, "Honedge", "Steel", "Ghost", 6, "Honedge is a sword Pokémon that is haunted.");
        addPokemon(db, "Doublade", "Steel", "Ghost", 6, "Doublade is the evolved form of Honedge, two swords linked.");
        addPokemon(db, "Aegislash", "Steel", "Ghost", 6, "Aegislash is the final form of Honedge, a powerful warrior.");
        addPokemon(db, "Spritzee", "Fairy", "", 6, "Spritzee is a small fairy Pokémon that emits a sweet fragrance.");
        addPokemon(db, "Aromatisse", "Fairy", "", 6, "Aromatisse is the evolved form of Spritzee, known for its perfume.");
        addPokemon(db, "Swirlix", "Fairy", "", 6, "Swirlix is a cotton candy Pokémon that loves sweets.");
        addPokemon(db, "Slurpuff", "Fairy", "", 6, "Slurpuff is the evolved form of Swirlix, known for its sense of smell.");
        addPokemon(db, "Inkay", "Dark", "Psychic", 6, "Inkay is a small squid Pokémon that can flip upside down.");
        addPokemon(db, "Malamar", "Dark", "Psychic", 6, "Malamar is the evolved form of Inkay, known for its cunning nature.");
        addPokemon(db, "Binacle", "Rock", "Water", 6, "Binacle is a small Pokémon that resembles two barnacles.");
        addPokemon(db, "Barbaracle", "Rock", "Water", 6, "Barbaracle is the evolved form of Binacle, powerful and robust.");
        addPokemon(db, "Clauncher", "Water", "", 6, "Clauncher is a small shrimp Pokémon known for its cannon-like claws.");
        addPokemon(db, "Clawitzer", "Water", "", 6, "Clawitzer is the evolved form of Clauncher, a formidable opponent.");
        addPokemon(db, "Helioptile", "Electric", "Normal", 6, "Helioptile is a small lizard Pokémon that can generate electricity.");
        addPokemon(db, "Heliolisk", "Electric", "Normal", 6, "Heliolisk is the evolved form of Helioptile, agile and quick.");
        addPokemon(db, "Tyrunt", "Rock", "Dragon", 6, "Tyrunt is a dinosaur Pokémon that loves to play.");
        addPokemon(db, "Tyrantrum", "Rock", "Dragon", 6, "Tyrantrum is the evolved form of Tyrunt, a powerful dinosaur.");
        addPokemon(db, "Amaura", "Rock", "Ice", 6, "Amaura is a small dinosaur Pokémon that resembles an aurora.");
        addPokemon(db, "Aurorus", "Rock", "Ice", 6, "Aurorus is the evolved form of Amaura, majestic and graceful.");
        addPokemon(db, "Sylveon", "Fairy", "", 6, "Sylveon is an evolution of Eevee, known for its ribbons and grace.");
        addPokemon(db, "Hawlucha", "Fighting", "Flying", 6, "Hawlucha is a wrestling Pokémon that combines agility and strength.");
        addPokemon(db, "Dedenne", "Electric", "Fairy", 6, "Dedenne is a small mouse Pokémon known for its cute appearance.");
        addPokemon(db, "Go Go", "Grass", "", 6, "Gogoat is a larger form of Skiddo, strong and dependable.");
        addPokemon(db, "Porygon-Z", "Normal", "", 6, "Porygon-Z is a digital Pokémon with advanced programming.");
        addPokemon(db, "Xerneas", "Fairy", "", 6, "Xerneas is a legendary Pokémon known for its life-giving powers.");
        addPokemon(db, "Yveltal", "Dark", "Flying", 6, "Yveltal is a legendary Pokémon known for its destructive powers.");
        addPokemon(db, "Zygarde", "Dragon", "Ground", 6, "Zygarde is a legendary Pokémon that maintains the balance of nature.");
        addPokemon(db, "Diancie", "Rock", "Fairy", 6, "Diancie is a mythical Pokémon that creates diamonds.");
        addPokemon(db, "Hoopa", "Psychic", "Ghost", 6, "Hoopa is a mythical Pokémon known for its mischief.");
        addPokemon(db, "Volcanion", "Fire", "Water", 6, "Volcanion is a mythical Pokémon that can control steam.");
        //GEN 7
        addPokemon(db, "Rowlet", "Grass", "Flying", 7, "Rowlet is a small owl Pokémon that can glide silently.");
        addPokemon(db, "Dartrix", "Grass", "Flying", 7, "Dartrix is the evolved form of Rowlet, known for its bowtie.");
        addPokemon(db, "Decidueye", "Grass", "Ghost", 7, "Decidueye is the final form of Rowlet, a master archer.");
        addPokemon(db, "Litten", "Fire", "", 7, "Litten is a small fire kitten Pokémon that loves to nap.");
        addPokemon(db, "Torracat", "Fire", "", 7, "Torracat is the evolved form of Litten, known for its bell.");
        addPokemon(db, "Incineroar", "Fire", "Dark", 7, "Incineroar is the final form of Litten, a fierce wrestler.");
        addPokemon(db, "Popplio", "Water", "", 7, "Popplio is a small sea lion Pokémon that loves to perform.");
        addPokemon(db, "Brionne", "Water", "", 7, "Brionne is the evolved form of Popplio, known for its singing.");
        addPokemon(db, "Primarina", "Water", "Fairy", 7, "Primarina is the final form of Popplio, a graceful performer.");
        addPokemon(db, "Pikipek", "Normal", "Flying", 7, "Pikipek is a small woodpecker Pokémon known for its pecking.");
        addPokemon(db, "Trumbeak", "Normal", "Flying", 7, "Trumbeak is the evolved form of Pikipek, a loud bird.");
        addPokemon(db, "Toucannon", "Normal", "Flying", 7, "Toucannon is the final form of Pikipek, known for its beak.");
        addPokemon(db, "Yungoos", "Normal", "", 7, "Yungoos is a small mongoose Pokémon that loves to hunt.");
        addPokemon(db, "Gumshoos", "Normal", "", 7, "Gumshoos is the evolved form of Yungoos, a vigilant Pokémon.");
        addPokemon(db, "Grubbin", "Bug", "", 7, "Grubbin is a small bug Pokémon that loves to eat.");
        addPokemon(db, "Charjabug", "Bug", "Electric", 7, "Charjabug is the evolved form of Grubbin, a battery Pokémon.");
        addPokemon(db, "Vikavolt", "Bug", "Electric", 7, "Vikavolt is the final form of Grubbin, known for its speed.");
        addPokemon(db, "Crabrawler", "Fighting", "", 7, "Crabrawler is a crab Pokémon known for its tough claws.");
        addPokemon(db, "Crabominable", "Fighting", "Ice", 7, "Crabominable is the evolved form of Crabrawler, a strong fighter.");
        addPokemon(db, "Oricorio", "Fire", "Flying", 7, "Oricorio is a bird Pokémon with different forms based on dance.");
        addPokemon(db, "Cutiefly", "Bug", "Fairy", 7, "Cutiefly is a small fairy Pokémon that loves nectar.");
        addPokemon(db, "Ribombee", "Bug", "Fairy", 7, "Ribombee is the evolved form of Cutiefly, known for its pollen.");
        addPokemon(db, "Rockruff", "Rock", "", 7, "Rockruff is a small puppy Pokémon that is very loyal.");
        addPokemon(db, "Lycanroc", "Rock", "", 7, "Lycanroc has different forms and is known for its fierce nature.");
        addPokemon(db, "Wishiwashi", "Water", "", 7, "Wishiwashi is a small fish Pokémon that can form a school.");
        addPokemon(db, "Wishiwashi (School Form)", "Water", "", 7, "In its school form, Wishiwashi becomes powerful and intimidating.");
        addPokemon(db, "Marainer", "Water", "Ice", 7, "Marainer is a small fish Pokémon that loves to swim.");
        addPokemon(db, "Morelull", "Grass", "Fairy", 7, "Morelull is a small mushroom Pokémon that emits light.");
        addPokemon(db, "Shiinotic", "Grass", "Fairy", 7, "Shiinotic is the evolved form of Morelull, known for its spores.");
        addPokemon(db, "Salandit", "Fire", "Poison", 7, "Salandit is a small lizard Pokémon that can create fire.");
        addPokemon(db, "Salazzle", "Fire", "Poison", 7, "Salazzle is the evolved form of Salandit, known for its cunning.");
        addPokemon(db, "Stufful", "Normal", "Fighting", 7, "Stufful is a small bear Pokémon that loves to cuddle.");
        addPokemon(db, "Bewear", "Normal", "Fighting", 7, "Bewear is the evolved form of Stufful, known for its strength.");
        addPokemon(db, "Bounsweet", "Grass", "", 7, "Bounsweet is a small fruit Pokémon that is very sweet.");
        addPokemon(db, "Steenee", "Grass", "", 7, "Steenee is the evolved form of Bounsweet, elegant and proud.");
        addPokemon(db, "Tsareena", "Grass", "", 7, "Tsareena is the final form of Bounsweet, a regal Pokémon.");
        addPokemon(db, "Comfey", "Fairy", "", 7, "Comfey is a small Pokémon that creates floral leis.");
        addPokemon(db, "Oranguru", "Normal", "Psychic", 7, "Oranguru is a wise Pokémon that assists others.");
        addPokemon(db, "Passimian", "Fighting", "", 7, "Passimian is a team player Pokémon that works well in groups.");
        addPokemon(db, "Wimpod", "Bug", "Water", 7, "Wimpod is a small, cowardly Pokémon that hides from danger.");
        addPokemon(db, "Golisopod", "Bug", "Water", 7, "Golisopod is the evolved form of Wimpod, a fearsome fighter.");
        addPokemon(db, "Sandygast", "Ghost", "Ground", 7, "Sandygast is a sandcastle Pokémon that absorbs life.");
        addPokemon(db, "Palossand", "Ghost", "Ground", 7, "Palossand is the evolved form of Sandygast, a ghostly fortress.");
        addPokemon(db, "Pyukumuku", "Water", "", 7, "Pyukumuku is a small sea cucumber Pokémon that can regenerate.");
        addPokemon(db, "Type: Null", "Normal", "", 7, "Type: Null is an experimental Pokémon created to stabilize emotions.");
        addPokemon(db, "Silvally", "Normal", "", 7, "Silvally is the evolved form of Type: Null, known for its adaptability.");
        addPokemon(db, "Minior", "Rock", "Flying", 7, "Minior is a small meteor Pokémon that can change its color.");
        addPokemon(db, "Minior (Core Form)", "Rock", "Flying", 7, "In its core form, Minior is more colorful and energetic.");
        addPokemon(db, "Komala", "Normal", "", 7, "Komala is a koala Pokémon that is always asleep.");
        addPokemon(db, "Turtonator", "Fire", "Dragon", 7, "Turtonator is a turtle Pokémon that can create explosive blasts.");
        addPokemon(db, "Togedemaru", "Electric", "Steel", 7, "Togedemaru is a small round Pokémon known for its spiky fur.");
        addPokemon(db, "Mimikyu", "Ghost", "Fairy", 7, "Mimikyu is a ghost Pokémon that disguises itself as Pikachu.");
        addPokemon(db, "Bruxish", "Water", "Psychic", 7, "Bruxish is a colorful fish Pokémon known for its fierce bite.");
        addPokemon(db, "Drampa", "Normal", "Dragon", 7, "Drampa is a dragon Pokémon known for its kind demeanor.");
        addPokemon(db, "Dhelmise", "Ghost", "Grass", 7, "Dhelmise is an anchor Pokémon that drifts in the ocean.");
        addPokemon(db, "Jangmo-o", "Dragon", "", 7, "Jangmo-o is a small dragon Pokémon that is very shy.");
        addPokemon(db, "Hakamo-o", "Dragon", "Fighting", 7, "Hakamo-o is the evolved form of Jangmo-o, a proud warrior.");
        addPokemon(db, "Kommo-o", "Dragon", "Fighting", 7, "Kommo-o is the final form of Jangmo-o, known for its battle skills.");
        addPokemon(db, "Tapu Koko", "Electric", "Fairy", 7, "Tapu Koko is a guardian deity Pokémon known for its speed.");
        addPokemon(db, "Tapu Lele", "Psychic", "Fairy", 7, "Tapu Lele is a guardian deity Pokémon known for its healing.");
        addPokemon(db, "Tapu Bulu", "Grass", "Fairy", 7, "Tapu Bulu is a guardian deity Pokémon that protects nature.");
        addPokemon(db, "Tapu Fini", "Water", "Fairy", 7, "Tapu Fini is a guardian deity Pokémon known for its mist.");
        addPokemon(db, "Cosmog", "Psychic", "", 7, "Cosmog is a small, nebula-like Pokémon that is very rare.");
        addPokemon(db, "Cosmoem", "Psychic", "", 7, "Cosmoem is the evolved form of Cosmog, a dormant Pokémon.");
        addPokemon(db, "Solgaleo", "Psychic", "Steel", 7, "Solgaleo is a legendary Pokémon known as the sun incarnate.");
        addPokemon(db, "Lunala", "Psychic", "Ghost", 7, "Lunala is a legendary Pokémon known as the moon incarnate.");
        addPokemon(db, "Nihilego", "Rock", "Poison", 7, "Nihilego is an Ultra Beast known for its unique form.");
        addPokemon(db, "Buzzwole", "Bug", "Fighting", 7, "Buzzwole is an Ultra Beast known for its muscular build.");
        addPokemon(db, "Pheromosa", "Bug", "Fighting", 7, "Pheromosa is an Ultra Beast known for its speed.");
        addPokemon(db, "Xurkitree", "Electric", "", 7, "Xurkitree is an Ultra Beast that resembles a power line.");
        addPokemon(db, "Celesteela", "Steel", "Flying", 7, "Celesteela is an Ultra Beast known for its metallic body.");
        addPokemon(db, "Kartana", "Grass", "Steel", 7, "Kartana is an Ultra Beast known for its sharp blades.");
        addPokemon(db, "Guzzlord", "Dark", "Dragon", 7, "Guzzlord is an Ultra Beast known for its massive appetite.");
        addPokemon(db, "Necrozma", "Psychic", "", 7, "Necrozma is a legendary Pokémon known for its light absorption.");
        addPokemon(db, "Necrozma (Dusk Mane)", "Psychic", "Steel", 7, "Necrozma's Dusk Mane form is powerful and noble.");
        addPokemon(db, "Necrozma (Dawn Wings)", "Psychic", "Ghost", 7, "Necrozma's Dawn Wings form is mystical and ethereal.");
        addPokemon(db, "Necrozma (Ultra)", "Psychic", "Dragon", 7, "Necrozma's Ultra form is its most powerful state.");
        addPokemon(db, "Magearna", "Steel", "Fairy", 7, "Magearna is an artificial Pokémon with a mysterious heart.");
        addPokemon(db, "Marshadow", "Fighting", "Ghost", 7, "Marshadow is a shadowy Pokémon known for its stealth.");
        addPokemon(db, "Zeraora", "Electric", "", 7, "Zeraora is a mythical Pokémon known for its speed and agility.");
        addPokemon(db, "Meltan", "Steel", "", 7, "Meltan is a mythical Pokémon that can change shape.");
        addPokemon(db, "Melmetal", "Steel", "", 7, "Melmetal is the evolved form of Meltan, a powerful Pokémon.");
        //GEN 8
        addPokemon(db, "Grookey", "Grass", "", 8, "Grookey is a small monkey Pokémon that loves to play drums.");
        addPokemon(db, "Thwackey", "Grass", "", 8, "Thwackey is the evolved form of Grookey, known for its musical talent.");
        addPokemon(db, "Rillaboom", "Grass", "", 8, "Rillaboom is the final form of Grookey, a powerful drummer.");
        addPokemon(db, "Scorbunny", "Fire", "", 8, "Scorbunny is a small rabbit Pokémon that loves to run.");
        addPokemon(db, "Raboot", "Fire", "", 8, "Raboot is the evolved form of Scorbunny, a more agile Pokémon.");
        addPokemon(db, "Cinderace", "Fire", "", 8, "Cinderace is the final form of Scorbunny, a skilled striker.");
        addPokemon(db, "Sobble", "Water", "", 8, "Sobble is a small lizard Pokémon that can turn invisible.");
        addPokemon(db, "Drizzile", "Water", "", 8, "Drizzile is the evolved form of Sobble, known for its stealth.");
        addPokemon(db, "Inteleon", "Water", "", 8, "Inteleon is the final form of Sobble, a master sniper.");
        addPokemon(db, "Skwovet", "Normal", "", 8, "Skwovet is a small squirrel Pokémon that hoards food.");
        addPokemon(db, "Greedent", "Normal", "", 8, "Greedent is the evolved form of Skwovet, known for its greed.");
        addPokemon(db, "Rookidee", "Flying", "", 8, "Rookidee is a small bird Pokémon known for its speed.");
        addPokemon(db, "Corvisquire", "Flying", "", 8, "Corvisquire is the evolved form of Rookidee, a clever bird.");
        addPokemon(db, "Corviknight", "Flying", "Steel", 8, "Corviknight is the final form of Rookidee, a strong protector.");
        addPokemon(db, "Blipbug", "Bug", "", 8, "Blipbug is a small bug Pokémon that can communicate.");
        addPokemon(db, "Dottler", "Bug", "Psychic", 8, "Dottler is the evolved form of Blipbug, known for its patterns.");
        addPokemon(db, "Orbeetle", "Bug", "Psychic", 8, "Orbeetle is the final form of Blipbug, a brilliant strategist.");
        addPokemon(db, "Nickit", "Dark", "", 8, "Nickit is a small fox Pokémon known for its stealthy nature.");
        addPokemon(db, "Thievul", "Dark", "", 8, "Thievul is the evolved form of Nickit, a cunning thief.");
        addPokemon(db, "Gossifleur", "Grass", "", 8, "Gossifleur is a small flower Pokémon that loves sunlight.");
        addPokemon(db, "Eldegoss", "Grass", "", 8, "Eldegoss is the evolved form of Gossifleur, known for its fluff.");
        addPokemon(db, "Wooloo", "Normal", "", 8, "Wooloo is a fluffy sheep Pokémon that loves to roll.");
        addPokemon(db, "Dubwool", "Normal", "", 8, "Dubwool is the evolved form of Wooloo, a strong herd Pokémon.");
        addPokemon(db, "Chewtle", "Water", "Rock", 8, "Chewtle is a small turtle Pokémon that enjoys sunbathing.");
        addPokemon(db, "Drednaw", "Water", "Rock", 8, "Drednaw is the evolved form of Chewtle, a fierce fighter.");
        addPokemon(db, "Yamper", "Electric", "", 8, "Yamper is a small puppy Pokémon that loves to chase.");
        addPokemon(db, "Boltund", "Electric", "", 8, "Boltund is the evolved form of Yamper, known for its speed.");
        addPokemon(db, "Rolycoly", "Rock", "", 8, "Rolycoly is a small coal Pokémon that rolls around.");
        addPokemon(db, "Carkol", "Rock", "Fire", 8, "Carkol is the evolved form of Rolycoly, a train Pokémon.");
        addPokemon(db, "Coalossal", "Rock", "Fire", 8, "Coalossal is the final form of Rolycoly, a powerful Pokémon.");
        addPokemon(db, "Applin", "Grass", "Dragon", 8, "Applin is a small apple Pokémon that hides in fruit.");
        addPokemon(db, "Flapple", "Grass", "Dragon", 8, "Flapple is the evolved form of Applin, a dragon that loves apples.");
        addPokemon(db, "Appletun", "Grass", "Dragon", 8, "Appletun is the evolved form of Applin, a sweet Pokémon.");
        addPokemon(db, "Silicobra", "Ground", "", 8, "Silicobra is a snake Pokémon that burrows in the sand.");
        addPokemon(db, "Sandaconda", "Ground", "", 8, "Sandaconda is the evolved form of Silicobra, a strong fighter.");
        addPokemon(db, "Cufant", "Steel", "", 8, "Cufant is a small elephant Pokémon known for its strength.");
        addPokemon(db, "Copperajah", "Steel", "", 8, "Copperajah is the evolved form of Cufant, a powerful guardian.");
        addPokemon(db, "Dracozolt", "Electric", "Dragon", 8, "Dracozolt is a fossil Pokémon that resembles a dinosaur.");
        addPokemon(db, "Arctozolt", "Ice", "Electric", 8, "Arctozolt is a fossil Pokémon that resembles a prehistoric creature.");
        addPokemon(db, "Dracovish", "Water", "Dragon", 8, "Dracovish is a fossil Pokémon that resembles a fish.");
        addPokemon(db, "Arctovish", "Ice", "Water", 8, "Arctovish is a fossil Pokémon that resembles a fish with ice powers.");
        addPokemon(db, "Duraludon", "Steel", "Dragon", 8, "Duraludon is a skyscraper Pokémon known for its resilience.");
        addPokemon(db, "Mega Duraludon", "Steel", "Dragon", 8, "Mega Duraludon is a powerful version of Duraludon.");
        addPokemon(db, "Mega Tyranitar", "Rock", "Dark", 8, "Mega Tyranitar is a powerful evolution of Tyranitar.");
        addPokemon(db, "Mega Scizor", "Bug", "Steel", 8, "Mega Scizor is a powerful evolution of Scizor.");
        addPokemon(db, "Mega Gardevoir", "Psychic", "Fairy", 8, "Mega Gardevoir is a powerful evolution of Gardevoir.");
        addPokemon(db, "Zarude", "Dark", "Grass", 8, "Zarude is a mythical Pokémon that lives in the jungle.");
        addPokemon(db, "Regieleki", "Electric", "", 8, "Regieleki is a legendary Pokémon known for its speed.");
        addPokemon(db, "Regidrago", "Dragon", "", 8, "Regidrago is a legendary Pokémon known for its power.");
        addPokemon(db, "Glastrier", "Ice", "", 8, "Glastrier is a legendary Pokémon known for its strength.");
        addPokemon(db, "Spectrier", "Ghost", "", 8, "Spectrier is a legendary Pokémon known for its speed.");
        addPokemon(db, "Calyrex", "Psychic", "Grass", 8, "Calyrex is a legendary Pokémon that rules over Galar.");
        //GEN 9
        addPokemon(db, "Sprigatito", "Grass", "", 9, "Sprigatito is a cute cat Pokémon that loves to play.");
        addPokemon(db, "Floragato", "Grass", "", 9, "Floragato is the evolved form of Sprigatito, known for its agility.");
        addPokemon(db, "Meowscarada", "Grass", "Dark", 9, "Meowscarada is the final form of Sprigatito, a master of disguise.");
        addPokemon(db, "Fuecoco", "Fire", "", 9, "Fuecoco is a small crocodile Pokémon that loves to nap.");
        addPokemon(db, "Crocalor", "Fire", "", 9, "Crocalor is the evolved form of Fuecoco, a more active Pokémon.");
        addPokemon(db, "Skeledirge", "Fire", "Ghost", 9, "Skeledirge is the final form of Fuecoco, a powerful singer.");
        addPokemon(db, "Quaxly", "Water", "", 9, "Quaxly is a duck Pokémon known for its charm.");
        addPokemon(db, "Quaxwell", "Water", "", 9, "Quaxwell is the evolved form of Quaxly, a strong swimmer.");
        addPokemon(db, "Quaquaval", "Water", "Flying", 9, "Quaquaval is the final form of Quaxly, a skilled dancer.");
        addPokemon(db, "Lechonk", "Normal", "", 9, "Lechonk is a small pig Pokémon that loves to eat.");
        addPokemon(db, "Oinkologne", "Normal", "", 9, "Oinkologne is the evolved form of Lechonk, known for its size.");
        addPokemon(db, "Tinkaton", "Fairy", "Steel", 9, "Tinkaton is a fairy Pokémon known for its hammer.");
        addPokemon(db, "Tinkaton", "Fairy", "Steel", 9, "Tinkaton is a fairy Pokémon known for its hammer.");
        addPokemon(db, "Pawmi", "Electric", "", 9, "Pawmi is a small mouse Pokémon that loves to spark.");
        addPokemon(db, "Pawmo", "Electric", "Fighting", 9, "Pawmo is the evolved form of Pawmi, a brave fighter.");
        addPokemon(db, "Pachirisu", "Electric", "", 9, "Pachirisu is a small squirrel Pokémon that loves to collect.");
        addPokemon(db, "Pawmo", "Electric", "Fighting", 9, "Pawmo is the evolved form of Pawmi, a brave fighter.");
        addPokemon(db, "Dudunsparce", "Normal", "", 9, "Dudunsparce is a snake Pokémon known for its long body.");
        addPokemon(db, "Dudunsparce", "Normal", "", 9, "Dudunsparce is a snake Pokémon known for its long body.");
        addPokemon(db, "Cetoddle", "Ice", "", 9, "Cetoddle is a small ice Pokémon that loves to slide.");
        addPokemon(db, "Cetitan", "Ice", "", 9, "Cetitan is the evolved form of Cetoddle, a massive creature.");
        addPokemon(db, "Kapow", "Fighting", "", 9, "Kapow is a powerful fighting Pokémon known for its punches.");
        addPokemon(db, "Iron Treads", "Ground", "Steel", 9, "Iron Treads is a powerful robot Pokémon known for its speed.");
        addPokemon(db, "Iron Bundle", "Ice", "Water", 9, "Iron Bundle is a robot Pokémon known for its agility.");
        addPokemon(db, "Roovolt", "Electric", "", 9, "Roovolt is a new electric Pokémon with fast movements.");
        addPokemon(db, "Cyclizar", "Dragon", "Normal", 9, "Cyclizar is a lizard Pokémon known for its speed.");
        addPokemon(db, "Koraidon", "Dragon", "Fighting", 9, "Koraidon is a legendary Pokémon known for its power.");
        addPokemon(db, "Miraidon", "Electric", "Dragon", 9, "Miraidon is a legendary Pokémon known for its technology.");
        addPokemon(db, "Chien-Pao", "Ice", "Dark", 9, "Chien-Pao is a legendary Pokémon that resembles a wolf.");
        addPokemon(db, "Ting-Lu", "Ground", "Dark", 9, "Ting-Lu is a legendary Pokémon that resembles a bull.");
        addPokemon(db, "Wo-Chien", "Grass", "Dark", 9, "Wo-Chien is a legendary Pokémon that resembles a lizard.");
        addPokemon(db, "Chi-Yu", "Fire", "Dark", 9, "Chi-Yu is a legendary Pokémon that resembles a fish.");
        addPokemon(db, "Gholdengo", "Steel", "Ghost", 9, "Gholdengo is a Pokémon made of coins, known for its power.");
        addPokemon(db, "Baxcalibur", "Dragon", "Ice", 9, "Baxcalibur is a dragon Pokémon known for its strength.");
        addPokemon(db, "Walking Wake", "Water", "Dragon", 9, "Walking Wake is a legendary Pokémon known for its agility.");
        addPokemon(db, "Iron Valiant", "Fairy", "Fighting", 9, "Iron Valiant is a powerful robot Pokémon known for its speed.");
        addPokemon(db, "Fidough", "Fairy", "", 9, "Fidough is a bread dog Pokémon that loves to play.");
        addPokemon(db, "Dachsbun", "Fairy", "", 9, "Dachsbun is the evolved form of Fidough, known for its loyalty.");
        addPokemon(db, "Smoliv", "Grass", "Normal", 9, "Smoliv is a small olive Pokémon that enjoys sunlight.");
        addPokemon(db, "Dolliv", "Grass", "Normal", 9, "Dolliv is the evolved form of Smoliv, a more mature Pokémon.");
        addPokemon(db, "Arboliva", "Grass", "Normal", 9, "Arboliva is the final form of Smoliv, a wise protector.");
        addPokemon(db, "Tinkaton", "Fairy", "Steel", 9, "Tinkaton is a fairy Pokémon known for its hammer.");
    }

    private static void addPokemon(SQLiteDatabase db, String name, String type1, String type2, int generation, String description) {
        ContentValues values = new ContentValues();
        values.put(DatabaseHelper.COLUMN_NAME, name);
        values.put(DatabaseHelper.COLUMN_TYPE1, type1);
        values.put(DatabaseHelper.COLUMN_TYPE2, type2);
        values.put(DatabaseHelper.COLUMN_GENERATION, generation);
        values.put(DatabaseHelper.COLUMN_DESCRIPTION, description);
        db.insert(DatabaseHelper.TABLE_POKEMON, null, values);
    }
}
