package com.example.projeto_pokedex_app;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;

public class PokemonDataSeeder {

    public static void seedInitialData(SQLiteDatabase db) {
        addPokemon(db, "Bulbasaur", "Grass", "Poison", 1, "Bulbasaur is a small, quadruped Pokémon with a green body and a plant bulb on its back.");
        addPokemon(db, "Ivysaur", "Grass", "Poison", 1, "Ivysaur is the evolved form of Bulbasaur and has a large flower blooming on its back.");
        addPokemon(db, "Venusaur", "Grass", "Poison", 1, "Venusaur is the final form of Bulbasaur, with a massive flower that can absorb sunlight.");
        addPokemon(db, "Charmander", "Fire", "", 1, "Charmander is a small lizard-like Pokémon with a flame on its tail.");
        addPokemon(db, "Charmeleon", "Fire", "", 1, "Charmeleon is the evolved form of Charmander, known for its aggressive nature.");
        addPokemon(db, "Charizard", "Fire", "Flying", 1, "Charizard is the final form of Charmander, capable of breathing fire and flying.");
        addPokemon(db, "Squirtle", "Water", "", 1, "Squirtle is a small turtle Pokémon known for its water abilities.");
        addPokemon(db, "Wartortle", "Water", "", 1, "Wartortle is the evolved form of Squirtle, with a bushy tail.");
        addPokemon(db, "Blastoise", "Water", "", 1, "Blastoise is the final form of Squirtle, equipped with powerful water cannons.");
        addPokemon(db, "Caterpie", "Bug", "", 1, "Caterpie is a small caterpillar Pokémon known for its ability to evolve quickly.");
        addPokemon(db, "Metapod", "Bug", "", 1, "Metapod is the cocoon stage of Caterpie, known for its hard shell.");
        addPokemon(db, "Butterfree", "Bug", "Flying", 1, "Butterfree is the final form of Caterpie, known for its beautiful wings.");
        addPokemon(db, "Weedle", "Bug", "Poison", 1, "Weedle is a small, worm-like Pokémon that can produce a toxic stinger.");
        addPokemon(db, "Kakuna", "Bug", "Poison", 1, "Kakuna is the cocoon stage of Weedle, known for its hard exterior.");
        addPokemon(db, "Beedrill", "Bug", "Poison", 1, "Beedrill is the final form of Weedle, known for its stingers.");
        addPokemon(db, "Pidgey", "Normal", "Flying", 1, "Pidgey is a small bird Pokémon known for its flying abilities.");
        addPokemon(db, "Pidgeotto", "Normal", "Flying", 1, "Pidgeotto is the evolved form of Pidgey, known for its speed.");
        addPokemon(db, "Pidgeot", "Normal", "Flying", 1, "Pidgeot is the final form of Pidgey, known for its powerful wings.");
        addPokemon(db, "Rattata", "Normal", "", 1, "Rattata is a small rat Pokémon known for its quick movements.");
        addPokemon(db, "Raticate", "Normal", "", 1, "Raticate is the evolved form of Rattata, known for its large teeth.");
        addPokemon(db, "Spearow", "Normal", "Flying", 1, "Spearow is a small bird Pokémon known for its aggressive nature.");
        addPokemon(db, "Fearow", "Normal", "Flying", 1, "Fearow is the evolved form of Spearow, known for its speed and power.");
        addPokemon(db, "Ekans", "Poison", "", 1, "Ekans is a snake Pokémon that can coil around its prey.");
        addPokemon(db, "Arbok", "Poison", "", 1, "Arbok is the evolved form of Ekans, known for its intimidating hood.");
        addPokemon(db, "Pikachu", "Electric", "", 1, "Pikachu is a small, mouse-like Pokémon known for its electric abilities.");
        addPokemon(db, "Raichu", "Electric", "", 1, "Raichu is the evolved form of Pikachu and is larger and more powerful.");
        addPokemon(db, "Sandshrew", "Ground", "", 1, "Sandshrew is a small, burrowing Pokémon known for its hard shell.");
        addPokemon(db, "Sandslash", "Ground", "", 1, "Sandslash is the evolved form of Sandshrew, known for its sharp claws.");
        addPokemon(db, "Nidoran♀", "Poison", "", 1, "Nidoran♀ is a small, rabbit-like Pokémon known for its defensive capabilities.");
        addPokemon(db, "Nidorina", "Poison", "", 1, "Nidorina is the evolved form of Nidoran♀, known for its nurturing nature.");
        addPokemon(db, "Nidoqueen", "Poison", "Ground", 1, "Nidoqueen is the final form of Nidoran♀, known for its protective nature.");
        addPokemon(db, "Nidoran♂", "Poison", "", 1, "Nidoran♂ is a small, rabbit-like Pokémon known for its aggressive behavior.");
        addPokemon(db, "Nidorino", "Poison", "", 1, "Nidorino is the evolved form of Nidoran♂, known for its fighting abilities.");
        addPokemon(db, "Nidoking", "Poison", "Ground", 1, "Nidoking is the final form of Nidoran♂, known for its brute strength.");
        addPokemon(db, "Clefairy", "Fairy", "", 1, "Clefairy is a small, fairy-like Pokémon known for its playful nature.");
        addPokemon(db, "Clefable", "Fairy", "", 1, "Clefable is the evolved form of Clefairy, known for its magical abilities.");
        addPokemon(db, "Vulpix", "Fire", "", 1, "Vulpix is a small fox Pokémon known for its six orange tails.");
        addPokemon(db, "Ninetales", "Fire", "", 1, "Ninetales is the evolved form of Vulpix, known for its mystical powers.");
        addPokemon(db, "Jigglypuff", "Normal", "Fairy", 1, "Jigglypuff is a balloon-like Pokémon known for its singing ability.");
        addPokemon(db, "Wigglytuff", "Normal", "Fairy", 1, "Wigglytuff is the evolved form of Jigglypuff, known for its large size.");
        addPokemon(db, "Zubat", "Poison", "Flying", 1, "Zubat is a bat Pokémon known for its echolocation abilities.");
        addPokemon(db, "Golbat", "Poison", "Flying", 1, "Golbat is the evolved form of Zubat, known for its large fangs.");
        addPokemon(db, "Oddish", "Grass", "Poison", 1, "Oddish is a small plant Pokémon that can absorb sunlight.");
        addPokemon(db, "Gloom", "Grass", "Poison", 1, "Gloom is the evolved form of Oddish, known for its stinky odor.");
        addPokemon(db, "Vileplume", "Grass", "Poison", 1, "Vileplume is the final form of Oddish, known for its large flower.");
        addPokemon(db, "Paras", "Bug", "Grass", 1, "Paras is a bug Pokémon that is known for its mushroom-like parasites.");
        addPokemon(db, "Parasect", "Bug", "Grass", 1, "Parasect is the evolved form of Paras, known for its spores.");
        addPokemon(db, "Venonat", "Bug", "Poison", 1, "Venonat is a bug Pokémon known for its large, sensitive eyes.");
        addPokemon(db, "Venomoth", "Bug", "Poison", 1, "Venomoth is the evolved form of Venonat, known for its beautiful wings.");
        addPokemon(db, "Diglett", "Ground", "", 1, "Diglett is a small, mole-like Pokémon known for its underground abilities.");
        addPokemon(db, "Dugtrio", "Ground", "", 1, "Dugtrio is the evolved form of Diglett, known for its speed and teamwork.");
        addPokemon(db, "Meowth", "Normal", "", 1, "Meowth is a cat Pokémon known for its ability to speak.");
        addPokemon(db, "Persian", "Normal", "", 1, "Persian is the evolved form of Meowth, known for its elegance.");
        addPokemon(db, "Psyduck", "Water", "", 1, "Psyduck is a duck Pokémon known for its frequent headaches.");
        addPokemon(db, "Golduck", "Water", "", 1, "Golduck is the evolved form of Psyduck, known for its swimming abilities.");
        addPokemon(db, "Poliwag", "Water", "", 1, "Poliwag is a small tadpole Pokémon known for its spiral tail.");
        addPokemon(db, "Poliwhirl", "Water", "", 1, "Poliwhirl is the evolved form of Poliwag, known for its swirling pattern.");
        addPokemon(db, "Poliwrath", "Water", "Fighting", 1, "Poliwrath is the final form of Poliwag, known for its strength.");
        addPokemon(db, "Abra", "Psychic", "", 1, "Abra is a psychic Pokémon that is known for its teleportation ability.");
        addPokemon(db, "Kadabra", "Psychic", "", 1, "Kadabra is the evolved form of Abra, known for its psychic powers.");
        addPokemon(db, "Alakazam", "Psychic", "", 1, "Alakazam is the final form of Abra, known for its intelligence and speed.");
        addPokemon(db, "Machop", "Fighting", "", 1, "Machop is a small fighting Pokémon known for its strength.");
        addPokemon(db, "Machoke", "Fighting", "", 1, "Machoke is the evolved form of Machop, known for its muscles.");
        addPokemon(db, "Machamp", "Fighting", "", 1, "Machamp is the final form of Machop, known for its four arms.");
        addPokemon(db, "Bellsprout", "Grass", "Poison", 1, "Bellsprout is a plant Pokémon that can stand on its roots.");
        addPokemon(db, "Weepinbell", "Grass", "Poison", 1, "Weepinbell is the evolved form of Bellsprout, known for its bell shape.");
        addPokemon(db, "Victreebel", "Grass", "Poison", 1, "Victreebel is the final form of Bellsprout, known for its carnivorous nature.");
        addPokemon(db, "Tentacool", "Water", "Poison", 1, "Tentacool is a jellyfish Pokémon that can release toxins.");
        addPokemon(db, "Tentacruel", "Water", "Poison", 1, "Tentacruel is the evolved form of Tentacool, known for its large tentacles.");
        addPokemon(db, "Geodude", "Rock", "Ground", 1, "Geodude is a rock Pokémon that can be found in caves.");
        addPokemon(db, "Graveler", "Rock", "Ground", 1, "Graveler is the evolved form of Geodude, known for its boulders.");
        addPokemon(db, "Golem", "Rock", "Ground", 1, "Golem is the final form of Geodude, known for its hard shell.");
        addPokemon(db, "Ponyta", "Fire", "", 1, "Ponyta is a horse Pokémon known for its speed and fiery mane.");
        addPokemon(db, "Rapidash", "Fire", "", 1, "Rapidash is the evolved form of Ponyta, known for its elegance.");
        addPokemon(db, "Slowpoke", "Water", "Psychic", 1, "Slowpoke is a slow-moving Pokémon known for its laid-back nature.");
        addPokemon(db, "Slowbro", "Water", "Psychic", 1, "Slowbro is the evolved form of Slowpoke, known for its strong tail.");
        addPokemon(db, "Magnemite", "Electric", "Steel", 1, "Magnemite is a magnetic Pokémon that can levitate.");
        addPokemon(db, "Magneton", "Electric", "Steel", 1, "Magneton is the evolved form of Magnemite, known for its three units.");
        addPokemon(db, "Farfetch'd", "Normal", "Flying", 1, "Farfetch'd is a duck Pokémon known for carrying a leek.");
        addPokemon(db, "Doduo", "Normal", "Flying", 1, "Doduo is a bird Pokémon with two heads, known for its speed.");
        addPokemon(db, "Dodrio", "Normal", "Flying", 1, "Dodrio is the evolved form of Doduo, known for its three heads.");
        addPokemon(db, "Seel", "Water", "", 1, "Seel is a seal Pokémon known for its swimming abilities.");
        addPokemon(db, "Dewgong", "Water", "Ice", 1, "Dewgong is the evolved form of Seel, known for its gracefulness.");
        addPokemon(db, "Grimer", "Poison", "", 1, "Grimer is a sludge Pokémon that can be found in sewers.");
        addPokemon(db, "Muk", "Poison", "", 1, "Muk is the evolved form of Grimer, known for its toxic sludge.");
        addPokemon(db, "Shellder", "Water", "Ice", 1, "Shellder is a clam Pokémon known for its hard shell.");
        addPokemon(db, "Cloyster", "Water", "Ice", 1, "Cloyster is the evolved form of Shellder, known for its defensive abilities.");
        addPokemon(db, "Gastly", "Ghost", "Poison", 1, "Gastly is a ghost Pokémon that is made of gas.");
        addPokemon(db, "Haunter", "Ghost", "Poison", 1, "Haunter is the evolved form of Gastly, known for its floating hands.");
        addPokemon(db, "Gengar", "Ghost", "Poison", 1, "Gengar is the final form of Gastly, known for its mischievous nature.");
        addPokemon(db, "Onix", "Rock", "Ground", 1, "Onix is a rock snake Pokémon known for its size and strength.");
        addPokemon(db, "Drowzee", "Psychic", "", 1, "Drowzee is a Pokémon known for its ability to induce sleep.");
        addPokemon(db, "Hypno", "Psychic", "", 1, "Hypno is the evolved form of Drowzee, known for its hypnotic abilities.");
        addPokemon(db, "Krabby", "Water", "", 1, "Krabby is a small crab Pokémon known for its pincers.");
        addPokemon(db, "Kingler", "Water", "", 1, "Kingler is the evolved form of Krabby, known for its massive claw.");
        addPokemon(db, "Voltorb", "Electric", "", 1, "Voltorb is a ball-shaped Pokémon that resembles a Poké Ball.");
        addPokemon(db, "Electrode", "Electric", "", 1, "Electrode is the evolved form of Voltorb, known for its speed.");
        addPokemon(db, "Exeggcute", "Grass", "Psychic", 1, "Exeggcute is a group of eggs that are known for their psychic powers.");
        addPokemon(db, "Exeggutor", "Grass", "Psychic", 1, "Exeggutor is the evolved form of Exeggcute, known for its three heads.");
        addPokemon(db, "Cubone", "Ground", "", 1, "Cubone is a small Pokémon known for wearing its mother's skull.");
        addPokemon(db, "Marowak", "Ground", "", 1, "Marowak is the evolved form of Cubone, known for its bone club.");
        addPokemon(db, "Hitmonlee", "Fighting", "", 1, "Hitmonlee is a fighting Pokémon known for its powerful legs.");
        addPokemon(db, "Hitmonchan", "Fighting", "", 1, "Hitmonchan is a fighting Pokémon known for its boxing skills.");
        addPokemon(db, "Lickitung", "Normal", "", 1, "Lickitung is a Pokémon known for its long tongue.");
        addPokemon(db, "Koffing", "Poison", "", 1, "Koffing is a Pokémon filled with toxic gas.");
        addPokemon(db, "Weezing", "Poison", "", 1, "Weezing is the evolved form of Koffing, known for its two heads.");
        addPokemon(db, "Rhyhorn", "Ground", "Rock", 1, "Rhyhorn is a horned Pokémon known for its strength.");
        addPokemon(db, "Rhydon", "Ground", "Rock", 1, "Rhydon is the evolved form of Rhyhorn, known for its power.");
        addPokemon(db, "Chansey", "Normal", "", 1, "Chansey is a Pokémon known for its healing abilities.");
        addPokemon(db, "Tangela", "Grass", "", 1, "Tangela is a grass Pokémon covered in vines.");
        addPokemon(db, "Kangaskhan", "Normal", "", 1, "Kangaskhan is a kangaroo Pokémon known for carrying its baby in a pouch.");
        addPokemon(db, "Horsea", "Water", "", 1, "Horsea is a small seahorse Pokémon known for its swimming abilities.");
        addPokemon(db, "Seadra", "Water", "", 1, "Seadra is the evolved form of Horsea, known for its spines.");
        addPokemon(db, "Goldeen", "Water", "", 1, "Goldeen is a fish Pokémon known for its elegant fins.");
        addPokemon(db, "Seaking", "Water", "", 1, "Seaking is the evolved form of Goldeen, known for its large horn.");
        addPokemon(db, "Staryu", "Water", "", 1, "Staryu is a starfish Pokémon known for its glowing core.");
        addPokemon(db, "Starmie", "Water", "Psychic", 1, "Starmie is the evolved form of Staryu, known for its speed.");
        addPokemon(db, "Mr. Mime", "Psychic", "Fairy", 1, "Mr. Mime is a Pokémon known for its barrier techniques.");
        addPokemon(db, "Scyther", "Bug", "Flying", 1, "Scyther is a mantis Pokémon known for its speed and scythes.");
        addPokemon(db, "Jynx", "Ice", "Psychic", 1, "Jynx is a Pokémon known for its singing and ice powers.");
        addPokemon(db, "Electabuzz", "Electric", "", 1, "Electabuzz is an electric Pokémon known for its powerful attacks.");
        addPokemon(db, "Magmar", "Fire", "", 1, "Magmar is a fire Pokémon known for its fiery body.");
        addPokemon(db, "Pinsir", "Bug", "", 1, "Pinsir is a bug Pokémon known for its pincers.");
        addPokemon(db, "Tauros", "Normal", "", 1, "Tauros is a bull Pokémon known for its strength.");
        addPokemon(db, "Magikarp", "Water", "", 1, "Magikarp is a fish Pokémon known for its poor swimming ability.");
        addPokemon(db, "Gyarados", "Water", "Flying", 1, "Gyarados is the evolved form of Magikarp, known for its ferocity.");
        addPokemon(db, "Lapras", "Water", "Ice", 1, "Lapras is a Pokémon known for its ability to transport people.");
        addPokemon(db, "Ditto", "Normal", "", 1, "Ditto is a shape-shifting Pokémon known for its ability to imitate others.");
        addPokemon(db, "Eevee", "Normal", "", 1, "Eevee is known for its multiple evolutions.");
        addPokemon(db, "Vaporeon", "Water", "", 1, "Vaporeon is one of the possible evolutions of Eevee.");
        addPokemon(db, "Jolteon", "Electric", "", 1, "Jolteon is one of the possible evolutions of Eevee.");
        addPokemon(db, "Flareon", "Fire", "", 1, "Flareon is one of the possible evolutions of Eevee.");
        addPokemon(db, "Porygon", "Normal", "", 1, "Porygon is a digital Pokémon known for its adaptability.");
        addPokemon(db, "Omanyte", "Rock", "Water", 1, "Omanyte is a fossil Pokémon that is known for its shell.");
        addPokemon(db, "Omastar", "Rock", "Water", 1, "Omastar is the evolved form of Omanyte, known for its tentacles.");
        addPokemon(db, "Kabuto", "Rock", "Water", 1, "Kabuto is a fossil Pokémon that resembles a small crab.");
        addPokemon(db, "Kabutops", "Rock", "Water", 1, "Kabutops is the evolved form of Kabuto, known for its scythe-like arms.");
        addPokemon(db, "Aerodactyl", "Rock", "Flying", 1, "Aerodactyl is a fossil Pokémon known for its speed.");
        addPokemon(db, "Snorlax", "Normal", "", 1, "Snorlax is a Pokémon known for its huge size and slothful behavior.");
        addPokemon(db, "Articuno", "Ice", "Flying", 1, "Articuno is a legendary Pokémon known for its ice powers.");
        addPokemon(db, "Zapdos", "Electric", "Flying", 1, "Zapdos is a legendary Pokémon known for its electric powers.");
        addPokemon(db, "Moltres", "Fire", "Flying", 1, "Moltres is a legendary Pokémon known for its fiery wings.");
        addPokemon(db, "Dratini", "Dragon", "", 1, "Dratini is a dragon Pokémon known for its gentle nature.");
        addPokemon(db, "Dragonair", "Dragon", "", 1, "Dragonair is the evolved form of Dratini, known for its elegance.");
        addPokemon(db, "Dragonite", "Dragon", "", 1, "Dragonite is the final form of Dratini, known for its power.");
        addPokemon(db, "Mewtwo", "Psychic", "", 1, "Mewtwo is a legendary Pokémon known for its incredible psychic abilities.");
        addPokemon(db, "Mew", "Psychic", "Fairy", 1, "Mew is a mythical Pokémon known for its ability to learn any move.");
        // Continue adicionando Pokémon conforme necessário
    }

    private static void addPokemon(SQLiteDatabase db, String name, String type1, String type2, int generation, String description) {
        ContentValues values = new ContentValues();
        values.put(DatabaseHelper.COLUMN_NAME, name);
        values.put(DatabaseHelper.COLUMN_TYPE1, type1);
        values.put(DatabaseHelper.COLUMN_TYPE2, type2);
        values.put(DatabaseHelper.COLUMN_GENERATION, generation);
        values.put(DatabaseHelper.COLUMN_DESCRIPTION, description);
        db.insert(DatabaseHelper.TABLE_POKEMON, null, values);
    }
}
